CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/CHIRRTLDialect.cpp File Reference
CHIRRTLDialect.cpp File Reference
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpDefinition.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/FIRRTL/CHIRRTLTypes.cpp.inc"
#include "circt/Dialect/FIRRTL/CHIRRTL.cpp.inc"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.cpp.inc"
Macros
#define GET_TYPEDEF_CLASSES
#define GET_OP_CLASSES
#define GET_OP_LIST
#define GET_TYPEDEF_LIST
Functions
static ParseResult parseCHIRRTLOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printCHIRRTLOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseNameKind (OpAsmParser &parser, firrtl::NameKindEnumAttr &result)
static void printNameKind (OpAsmPrinter &p, Operation *op, firrtl::NameKindEnumAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseMemoryPortOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemoryPortOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "direction" and elide "annotations" if it exists or if it is empty.
static ParseResult parseMemoryDebugPortOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemoryDebugPortOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "direction" and elide "annotations" if it exists or if it is empty.
static ParseResult parseCombMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printCombMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseSeqMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printSeqMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 327 of file CHIRRTLDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 324 of file CHIRRTLDialect.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
parseCHIRRTLOp()
static ParseResult parseCHIRRTLOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 33 of file CHIRRTLDialect.cpp.
References circt::calyx::direction::get(), and isdigit.
Referenced by parseCombMemOp(), and parseSeqMemOp().
parseCombMemOp()
static ParseResult parseCombMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 241 of file CHIRRTLDialect.cpp.
References parseCHIRRTLOp().
parseMemoryDebugPortOp()
static ParseResult parseMemoryDebugPortOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 217 of file CHIRRTLDialect.cpp.
parseMemoryPortOp()
static ParseResult parseMemoryPortOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 161 of file CHIRRTLDialect.cpp.
parseNameKind()
static ParseResult parseNameKind (OpAsmParser & parser, firrtl::NameKindEnumAttr & result) static
Definition at line 86 of file CHIRRTLDialect.cpp.
References circt::calyx::direction::get().
parseSeqMemOp()
static ParseResult parseSeqMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 275 of file CHIRRTLDialect.cpp.
References parseCHIRRTLOp().
printCHIRRTLOp()
static void printCHIRRTLOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 54 of file CHIRRTLDialect.cpp.
Referenced by printCombMemOp(), and printSeqMemOp().
printCombMemOp()
static void printCombMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 246 of file CHIRRTLDialect.cpp.
References printCHIRRTLOp().
printMemoryDebugPortOp()
static void printMemoryDebugPortOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "direction" and elide "annotations" if it exists or if it is empty.
Definition at line 228 of file CHIRRTLDialect.cpp.
printMemoryPortOp()
static void printMemoryPortOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "direction" and elide "annotations" if it exists or if it is empty.
Definition at line 172 of file CHIRRTLDialect.cpp.
printNameKind()
static void printNameKind (OpAsmPrinter & p, Operation * op, firrtl::NameKindEnumAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 103 of file CHIRRTLDialect.cpp.
printSeqMemOp()
static void printSeqMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Definition at line 281 of file CHIRRTLDialect.cpp.
References printCHIRRTLOp().