CIRCT: circt::esi::ESIAPIType Class Reference
circt::esi::ESIAPIType Class Reference
#include <APIUtilities.h>
Public Types
using FieldInfo = hw::StructType::FieldInfo
Public Member Functions
ESIAPIType (mlir::Type)
virtual ~ESIAPIType ()=default
bool operator== (const ESIAPIType &) const
mlir::Type getType () const
Get the type back.
virtual bool isSupported () const
Returns true if the type is currently supported.
llvm::ArrayRef< FieldInfo > getFields () const
StringRef name () const
For now, the name is just the type serialized.
uint64_t typeID () const
Protected Attributes
llvm::SmallVector< FieldInfo > fieldTypes
Cosim requires that everything be contained in a struct.
mlir::Type type
std::string cachedName
std::optional< uint64_t > cachedID
Detailed Description
Definition at line 31 of file APIUtilities.h.
Member Typedef Documentation
FieldInfo
using circt::esi::ESIAPIType::FieldInfo = hw::StructType::FieldInfo
Definition at line 33 of file APIUtilities.h.
Constructor & Destructor Documentation
ESIAPIType()
circt::esi::ESIAPIType::ESIAPIType (mlir::Type)
Definition at line 57 of file APIUtilities.cpp.
References fieldTypes, circt::calyx::direction::get(), and type.
~ESIAPIType()
virtual circt::esi::ESIAPIType::~ESIAPIType () virtual default
Member Function Documentation
getFields()
llvm::ArrayRef<FieldInfo> circt::esi::ESIAPIType::getFields () const inline
Definition at line 45 of file APIUtilities.h.
References fieldTypes.
Referenced by circt::esi::capnp::detail::CapnpTypeSchemaImpl::buildDecoder(), circt::esi::capnp::detail::CapnpTypeSchemaImpl::size(), circt::esi::capnp::detail::CapnpTypeSchemaImpl::write(), circt::esi::cppapi::CPPType::write(), and circt::esi::cppapi::CPPType::writeReflection().
getType()
mlir::Type circt::esi::ESIAPIType::getType () const inline
Get the type back.
Definition at line 40 of file APIUtilities.h.
References type.
Referenced by circt::esi::capnp::detail::CapnpTypeSchemaImpl::buildDecoder(), and circt::esi::capnp::detail::CapnpTypeSchemaImpl::buildEncoder().
isSupported()
bool circt::esi::ESIAPIType::isSupported () const virtual
Returns true if the type is currently supported.
Reimplemented in circt::esi::cppapi::CPPType.
Definition at line 53 of file APIUtilities.cpp.
References circt::esi::isSupported(), and type.
Referenced by circt::esi::cppapi::CPPType::isSupported().
name()
StringRef circt::esi::ESIAPIType::name () const
For now, the name is just the type serialized.
This works only because we only support ints.
Definition at line 102 of file APIUtilities.cpp.
References cachedName, circt::esi::emitName(), type, and typeID().
Referenced by circt::esi::capnp::detail::CapnpTypeSchemaImpl::buildDecoder(), circt::esi::capnp::detail::CapnpTypeSchemaImpl::buildEncoder(), toJSON(), circt::esi::cppapi::CPPType::write(), and circt::esi::cppapi::CPPType::writeReflection().
operator==()
bool circt::esi::ESIAPIType::operator== (const ESIAPIType & that) const
Definition at line 73 of file APIUtilities.cpp.
References type.
typeID()
uint64_t circt::esi::ESIAPIType::typeID () const
Definition at line 113 of file APIUtilities.cpp.
References cachedID, circt::esi::esiApiVersion, and type.
Referenced by circt::esi::capnp::detail::CapnpTypeSchemaImpl::getCapnpTypeSchema(), name(), and toJSON().
Member Data Documentation
cachedID
std::optional<uint64_t> circt::esi::ESIAPIType::cachedID mutable protected
Definition at line 60 of file APIUtilities.h.
Referenced by typeID().
cachedName
std::string circt::esi::ESIAPIType::cachedName mutable protected
Definition at line 59 of file APIUtilities.h.
Referenced by name().
fieldTypes
llvm::SmallVector<FieldInfo> circt::esi::ESIAPIType::fieldTypes protected
Cosim requires that everything be contained in a struct.
ESI doesn't so we wrap non-struct types in a struct.
Definition at line 56 of file APIUtilities.h.
Referenced by ESIAPIType(), getFields(), and circt::esi::cppapi::CPPType::write().
type
mlir::Type circt::esi::ESIAPIType::type protected
Definition at line 58 of file APIUtilities.h.
Referenced by _fsm_ops_ext.MachineOp::__init__(), _hw_ops_ext.HWModuleOp::add_entry_block(), _msft_ops_ext.MSFTModuleOp::add_entry_block(), ESIAPIType(), getType(), _fsm_ops_ext.MachineOp::instantiate(), isSupported(), circt::esi::cppapi::CPPType::isSupported(), name(), operator==(), _hw_ops_ext.HWModuleOp::outputs(), and typeID().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/ESI/APIUtilities.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/APIUtilities.cpp