CIRCT: circt::esi::cppapi::CPPDesignModule Class Reference
circt::esi::cppapi::CPPDesignModule Class Reference
#include <CPPAPI.h>
Public Member Functions
CPPDesignModule (hw::HWModuleLike mod, SmallVectorImpl< ServiceHierarchyMetadataOp > &services, llvm::SmallVectorImpl< CPPService > &cppServices)
llvm::StringRef name ()
LogicalResult write (mlir::raw_indented_ostream &ios)
Private Attributes
hw::HWModuleLike mod
SmallVectorImpl< ServiceHierarchyMetadataOp > & services
SmallVectorImpl< CPPService > & cppServices
Detailed Description
Definition at line 97 of file CPPAPI.h.
Constructor & Destructor Documentation
CPPDesignModule()
circt::esi::cppapi::CPPDesignModule::CPPDesignModule (hw::HWModuleLike mod, SmallVectorImpl< ServiceHierarchyMetadataOp > & services, llvm::SmallVectorImpl< CPPService > & cppServices) inline
Definition at line 99 of file CPPAPI.h.
Member Function Documentation
name()
llvm::StringRef circt::esi::cppapi::CPPDesignModule::name () inline
Definition at line 104 of file CPPAPI.h.
References mod.
Referenced by write().
write()
LogicalResult CPPDesignModule::write (mlir::raw_indented_ostream & ios)
Definition at line 363 of file CPPAPI.cpp.
References cppServices, joinStringAttrArray(), lowercase(), mod, name(), and services.
Member Data Documentation
cppServices
SmallVectorImpl<CPPService>& circt::esi::cppapi::CPPDesignModule::cppServices private
Definition at line 110 of file CPPAPI.h.
Referenced by write().
mod
hw::HWModuleLike circt::esi::cppapi::CPPDesignModule::mod private
Definition at line 108 of file CPPAPI.h.
Referenced by name(), and write().
services
SmallVectorImpl<ServiceHierarchyMetadataOp>& circt::esi::cppapi::CPPDesignModule::services private
Definition at line 109 of file CPPAPI.h.
Referenced by write().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.cpp