CIRCT: circt::esi::cppapi::CPPService Class Reference
circt::esi::cppapi::CPPService Class Reference
#include <CPPAPI.h>
Public Member Functions
CPPService (esi::ServiceDeclOpInterface service, const llvm::MapVector< mlir::Type, CPPType > &types)
StringRef name () const
LogicalResult write (mlir::raw_indented_ostream &os)
esi::ServiceDeclOpInterface getService ()
llvm::SmallVector< ServicePortInfo > getPorts ()
CPPEndpoint * getPort (llvm::StringRef portName)
auto & getEndpoints ()
Private Attributes
esi::ServiceDeclOpInterface service
llvm::SmallVector< std::shared_ptr< CPPEndpoint > > endpoints
Detailed Description
Definition at line 71 of file CPPAPI.h.
Constructor & Destructor Documentation
CPPService()
CPPService::CPPService (esi::ServiceDeclOpInterface service, const llvm::MapVector< mlir::Type, CPPType > & types)
Definition at line 338 of file CPPAPI.cpp.
References endpoints, and service.
Member Function Documentation
getEndpoints()
auto& circt::esi::cppapi::CPPService::getEndpoints () inline
Definition at line 88 of file CPPAPI.h.
References endpoints.
getPort()
CPPEndpoint * CPPService::getPort (llvm::StringRef portName)
Definition at line 353 of file CPPAPI.cpp.
References endpoints.
getPorts()
llvm::SmallVector< esi::ServicePortInfo > CPPService::getPorts ()
Definition at line 347 of file CPPAPI.cpp.
References getService().
getService()
esi::ServiceDeclOpInterface circt::esi::cppapi::CPPService::getService () inline
Definition at line 84 of file CPPAPI.h.
References service.
Referenced by getPorts().
name()
StringRef circt::esi::cppapi::CPPService::name () const inline
Definition at line 77 of file CPPAPI.h.
References service.
Referenced by write().
write()
LogicalResult CPPService::write (mlir::raw_indented_ostream & os)
Definition at line 299 of file CPPAPI.cpp.
References endpoints, name(), and service.
Member Data Documentation
endpoints
llvm::SmallVector<std::shared_ptr<CPPEndpoint> > circt::esi::cppapi::CPPService::endpoints private
Definition at line 94 of file CPPAPI.h.
Referenced by CPPService(), getEndpoints(), getPort(), and write().
service
esi::ServiceDeclOpInterface circt::esi::cppapi::CPPService::service private
Definition at line 91 of file CPPAPI.h.
Referenced by CPPService(), getService(), name(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.cpp