CIRCT: circt::esi::cppapi::CPPType Class Reference
circt::esi::cppapi::CPPType Class Reference
#include <CPPAPI.h>
Public Member Functions
bool isSupported () const override
Returns true if the type is supported for the CPP API.
void writeCppName (llvm::raw_ostream &os) const
Write out the C++ name of this type.
mlir::LogicalResult write (mlir::raw_indented_ostream &os) const
Write out the type in its entirety.
void writeReflection (mlir::raw_indented_ostream &os, llvm::ArrayRef< std::string > namespaces) const
ESIAPIType (mlir::Type)
Public Member Functions inherited from circt::esi::ESIAPIType
ESIAPIType (mlir::Type)
virtual ~ESIAPIType ()=default
bool operator== (const ESIAPIType &) const
mlir::Type getType () const
Get the type back.
llvm::ArrayRef< FieldInfo > getFields () const
StringRef name () const
For now, the name is just the type serialized.
uint64_t typeID () const
Additional Inherited Members
Public Types inherited from circt::esi::ESIAPIType
using FieldInfo = hw::StructType::FieldInfo
Protected Attributes inherited from circt::esi::ESIAPIType
llvm::SmallVector< FieldInfo > fieldTypes
Cosim requires that everything be contained in a struct.
mlir::Type type
std::string cachedName
std::optional< uint64_t > cachedID
Detailed Description
Definition at line 34 of file CPPAPI.h.
Member Function Documentation
ESIAPIType()
circt::esi::ESIAPIType::ESIAPIType
Definition at line 35 of file APIUtilities.cpp.
isSupported()
bool CPPType::isSupported () const override virtual
Returns true if the type is supported for the CPP API.
Reimplemented from circt::esi::ESIAPIType.
Definition at line 216 of file CPPAPI.cpp.
References circt::esi::ESIAPIType::isSupported(), and circt::esi::ESIAPIType::type.
write()
LogicalResult CPPType::write (mlir::raw_indented_ostream & os) const
Write out the type in its entirety.
Definition at line 102 of file CPPAPI.cpp.
References emitCPPType(), circt::esi::ESIAPIType::fieldTypes, circt::esi::ESIAPIType::getFields(), isZeroWidthInt(), and circt::esi::ESIAPIType::name().
writeCppName()
void circt::esi::cppapi::CPPType::writeCppName (llvm::raw_ostream & os) const
Write out the C++ name of this type.
writeReflection()
void CPPType::writeReflection (mlir::raw_indented_ostream & os, llvm::ArrayRef< std::string > namespaces) const
Definition at line 221 of file CPPAPI.cpp.
References circt::esi::ESIAPIType::getFields(), and circt::esi::ESIAPIType::name().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.cpp