CIRCT: circt::firrtl::InstanceGraph Class Reference
circt::firrtl::InstanceGraph Class Reference
This graph tracks modules and where they are instantiated.
#include <FIRRTLInstanceGraph.h>
Public Member Functions
InstanceGraph (Operation *operation)
Create a new module graph of a circuit.
InstanceGraphNode * getTopLevelNode () override
Get the node corresponding to the top-level module of a circuit.
FModuleLike getTopLevelModule ()
Get the module corresponding to the top-level module of a circuit.
Public Member Functions inherited from circt::hw::InstanceGraphBase
virtual ~InstanceGraphBase ()
InstanceGraphNode * lookup (HWModuleLike op)
Look up an InstanceGraphNode for a module.
InstanceGraphNode * lookup (StringAttr name)
Lookup an module by name.
InstanceGraphNode * operator[] (HWModuleLike op)
Lookup an InstanceGraphNode for a module.
HWModuleLike getReferencedModule (HWInstanceLike op)
Look up the referenced module from an InstanceOp.
bool isAncestor (HWModuleLike child, HWModuleLike parent)
Check if child is instantiated by a parent.
FailureOr< llvm::ArrayRef< InstanceGraphNode * > > getInferredTopLevelNodes ()
Get the nodes corresponding to the inferred top-level modules of a circuit.
Operation * getParent ()
Return the parent under which all nodes are nested.
iterator begin ()
iterator end ()
virtual InstanceGraphNode * addModule (HWModuleLike module)
Add a newly created module to the instance graph.
virtual void erase (InstanceGraphNode *node)
Remove this module from the instance graph.
virtual void replaceInstance (HWInstanceLike inst, HWInstanceLike newInst)
Replaces an instance of a module with another instance.
Private Attributes
InstanceGraphNode * topLevelNode
Additional Inherited Members
Public Types inherited from circt::hw::InstanceGraphBase
using iterator = detail::AddressIterator< NodeList::iterator >
Iterate through all modules.
Static Public Member Functions inherited from circt::hw::InstanceGraphBase
static NodeList InstanceGraphBase::* getSublistAccess (Operation *)
Returns pointer to member of operation list.
Protected Member Functions inherited from circt::hw::InstanceGraphBase
InstanceGraphBase (Operation *parent)
Create a new module graph of a circuit.
InstanceGraphBase (const InstanceGraphBase &)=delete
InstanceGraphNode * getOrAddNode (StringAttr name)
Get the node corresponding to the module.
Protected Attributes inherited from circt::hw::InstanceGraphBase
Operation * parent
The node under which all modules are nested.
NodeList nodes
The storage for graph nodes, with deterministic iteration.
llvm::DenseMap< Attribute, InstanceGraphNode * > nodeMap
This maps each operation to its graph node.
llvm::SmallVector< InstanceGraphNode * > inferredTopLevelNodes
A caching of the inferred top level module(s).
Detailed Description
This graph tracks modules and where they are instantiated.
This is intended to be used as a cached analysis on FIRRTL circuits. This class can be used to walk the modules efficiently in a bottom-up or top-down order.
To use this class, retrieve a cached copy from the analysis manager: auto &instanceGraph = getAnalysis<InstanceGraph>(getOperation());
Definition at line 35 of file FIRRTLInstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraph()
InstanceGraph::InstanceGraph (Operation * operation) explicit
Create a new module graph of a circuit.
This must be called on a FIRRTL CircuitOp or MLIR ModuleOp.
Definition at line 23 of file FIRRTLInstanceGraph.cpp.
References circt::hw::InstanceGraphBase::getParent(), circt::hw::InstanceGraphBase::lookup(), and topLevelNode.
Member Function Documentation
getTopLevelModule()
FModuleLike circt::firrtl::InstanceGraph::getTopLevelModule () inline
Get the module corresponding to the top-level module of a circuit.
Definition at line 45 of file FIRRTLInstanceGraph.h.
References getTopLevelNode().
getTopLevelNode()
InstanceGraphNode* circt::firrtl::InstanceGraph::getTopLevelNode () inline override virtual
Get the node corresponding to the top-level module of a circuit.
Implements circt::hw::InstanceGraphBase.
Definition at line 42 of file FIRRTLInstanceGraph.h.
References topLevelNode.
Referenced by getTopLevelModule().
Member Data Documentation
topLevelNode
InstanceGraphNode* circt::firrtl::InstanceGraph::topLevelNode private
Definition at line 50 of file FIRRTLInstanceGraph.h.
Referenced by getTopLevelNode(), and InstanceGraph().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLInstanceGraph.cpp