CIRCT: LowerXMRPass Class Reference
LowerXMRPass Class Reference
The LowerXMRPass will replace every RefResolveOp with an XMR encoded within a verbatim expr op.
Classes
struct ValueComparator
llvm::EquivalenceClasses wants comparable elements.
Private Types
using nextNodeOnPath = std::optional< size_t >
refSendPathList is used to construct a path to the RefSendOp.
using node = std::pair< Attribute, nextNodeOnPath >
Private Member Functions
void runOnOperation () override
void getRefABIPrefix (FModuleLike mod, SmallVectorImpl< char > &prefix)
Generate the ABI ref_<circuit>_<module> prefix string into prefix.
StringAttr getRefABIMacroForPort (FModuleLike mod, size_t portIndex, const Twine &prefix, bool backTick=false)
Get full macro name as StringAttr for the specified ref port.
LogicalResult resolveReferencePath (mlir::TypedValue< RefType > refVal, ImplicitLocOpBuilder builder, mlir::FlatSymbolRefAttr &ref, SmallString< 128 > &stringLeaf)
LogicalResult resolveReference (mlir::TypedValue< RefType > refVal, Type desiredType, Location loc, Operation *insertBefore, Value &out)
LogicalResult handleForceReleaseOp (Operation *op)
LogicalResult handleRefResolve (RefResolveOp resolve)
void setPortToRemove (Operation *op, size_t index, size_t numPorts)
LogicalResult handleInstanceOp (InstanceOp inst, InstanceGraph &instanceGraph)
LogicalResult handlePublicModuleRefPorts (FModuleOp module)
ModuleNamespace & getModuleNamespace (FModuleLike module)
Get the cached namespace for a module.
InnerRefAttr getInnerRefTo (Value val)
InnerRefAttr getInnerRefTo (Operation *op)
void markForRemoval (Operation *op)
std::optional< size_t > getRemoteRefSend (Value val)
size_t addReachingSendsEntry (Value atRefVal, Attribute newRef, std::optional< size_t > continueFrom=std::nullopt)
void garbageCollect ()
bool isZeroWidth (FIRRTLBaseType t)
hw::HierPathOp getOrCreatePath (ArrayAttr pathArray, ImplicitLocOpBuilder &builder)
Return a HierPathOp for the provided pathArray.
Private Attributes
DenseMap< Operation *, ModuleNamespace > moduleNamespaces
Cached module namespaces.
DenseSet< Operation * > visitedModules
DenseMap< Value, size_t > dataflowAt
Map of a reference value to an entry into refSendPathList.
SmallVector< node > refSendPathList
llvm::EquivalenceClasses< Value, ValueComparator > * dataFlowClasses
DenseMap< Operation *, llvm::BitVector > refPortsToRemoveMap
SmallVector< Operation * > opsToRemove
RefResolve, RefSend, and Connects involving them that will be removed.
DenseMap< size_t, SmallString< 128 > > xmrPathSuffix
Record the internal path to an external module or a memory.
CircuitNamespace * circuitNamespace
DenseMap< Attribute, hw::HierPathOp > pathCache
A cache of already created HierPathOps.
OpBuilder::InsertPoint pathInsertPoint = {}
The insertion point where the pass inserts HierPathOps.
Detailed Description
The LowerXMRPass will replace every RefResolveOp with an XMR encoded within a verbatim expr op.
This also removes every RefType port from the modules and corresponding instances. This is a dataflow analysis over a very constrained RefType. Domain of the dataflow analysis is the set of all RefSendOps. It computes an interprocedural reaching definitions (of RefSendOp) analysis. Essentially every RefType value must be mapped to one and only one RefSendOp. The analysis propagates the dataflow from every RefSendOp to every value of RefType across modules. The RefResolveOp is the final leaf into which the dataflow must reach.
Since there can be multiple readers, multiple RefResolveOps can be reachable from a single RefSendOp. To support multiply instantiated modules and multiple readers, it is essential to track the path to the RefSendOp, other than just the RefSendOp. For example, if there exists a wire xmr_wire in module Foo, the algorithm needs to support generating Top.Bar.Foo.xmr_wire and Top.Foo.xmr_wire and Top.Zoo.Foo.xmr_wire for different instance paths that exist in the circuit.
Definition at line 50 of file LowerXMR.cpp.
Member Typedef Documentation
nextNodeOnPath
using LowerXMRPass::nextNodeOnPath = std::optional<size_t> private
refSendPathList is used to construct a path to the RefSendOp.
Each entry is a node, with an InnerRefAttr and a pointer to the next node in the path. The InnerRefAttr can be to an InstanceOp or to the XMR defining op. All the nodes representing an InstanceOp must have a valid nextNodeOnPath. Only the node representing the final XMR defining op has no nextNodeOnPath, which denotes a leaf node on the path.
Definition at line 723 of file LowerXMR.cpp.
node
using LowerXMRPass::node = std::pair<Attribute, nextNodeOnPath> private
Definition at line 724 of file LowerXMR.cpp.
Member Function Documentation
addReachingSendsEntry()
size_t LowerXMRPass::addReachingSendsEntry (Value atRefVal, Attribute newRef, std::optional< size_t > continueFrom = std::nullopt) inline private
Definition at line 595 of file LowerXMR.cpp.
garbageCollect()
void LowerXMRPass::garbageCollect () inline private
Definition at line 620 of file LowerXMR.cpp.
References builder.
getInnerRefTo() [1/2]
InnerRefAttr LowerXMRPass::getInnerRefTo (Operation * op) inline private
Definition at line 565 of file LowerXMR.cpp.
References circt::firrtl::getInnerRefTo().
getInnerRefTo() [2/2]
InnerRefAttr LowerXMRPass::getInnerRefTo (Value val) inline private
Definition at line 553 of file LowerXMR.cpp.
References circt::firrtl::getInnerRefTo().
getModuleNamespace()
ModuleNamespace& LowerXMRPass::getModuleNamespace (FModuleLike module) inline private
Get the cached namespace for a module.
Definition at line 545 of file LowerXMR.cpp.
getOrCreatePath()
hw::HierPathOp LowerXMRPass::getOrCreatePath (ArrayAttr pathArray, ImplicitLocOpBuilder & builder) inline private
Return a HierPathOp for the provided pathArray.
This will either return an existing HierPathOp or it will create and return a new one.
Definition at line 671 of file LowerXMR.cpp.
References builder.
getRefABIMacroForPort()
StringAttr LowerXMRPass::getRefABIMacroForPort (FModuleLike mod, size_t portIndex, const Twine & prefix, bool backTick = false) inline private
Get full macro name as StringAttr for the specified ref port.
Uses existing 'prefix', optionally preprends the backtick character.
Definition at line 295 of file LowerXMR.cpp.
References circt::calyx::direction::get().
getRefABIPrefix()
void LowerXMRPass::getRefABIPrefix (FModuleLike mod, SmallVectorImpl< char > & prefix) inline private
Generate the ABI ref_<circuit>_<module> prefix string into prefix.
Definition at line 286 of file LowerXMR.cpp.
References toVector().
getRemoteRefSend()
std::optional<size_t> LowerXMRPass::getRemoteRefSend (Value val) inline private
Definition at line 574 of file LowerXMR.cpp.
handleForceReleaseOp()
LogicalResult LowerXMRPass::handleForceReleaseOp (Operation * op) inline private
Definition at line 369 of file LowerXMR.cpp.
handleInstanceOp()
LogicalResult LowerXMRPass::handleInstanceOp (InstanceOp inst, InstanceGraph & instanceGraph) inline private
Get the resolution string for this ref-type port.
Definition at line 413 of file LowerXMR.cpp.
References circt::firrtl::getInnerRefTo(), circt::hw::InstanceGraphBase::getReferencedModule(), and circt::firrtl::Out.
handlePublicModuleRefPorts()
LogicalResult LowerXMRPass::handlePublicModuleRefPorts (FModuleOp module) inline private
Definition at line 497 of file LowerXMR.cpp.
References builder, circt::calyx::direction::get(), and circt::firrtl::Out.
handleRefResolve()
LogicalResult LowerXMRPass::handleRefResolve (RefResolveOp resolve) inline private
Definition at line 386 of file LowerXMR.cpp.
References builder, circt::calyx::direction::get(), circt::firrtl::getBitWidth(), and circt::firrtl::getIntZerosAttr().
isZeroWidth()
bool LowerXMRPass::isZeroWidth (FIRRTLBaseType t) inline private
Definition at line 667 of file LowerXMR.cpp.
References circt::firrtl::FIRRTLBaseType::getBitWidthOrSentinel().
markForRemoval()
void LowerXMRPass::markForRemoval (Operation * op) inline private
Definition at line 572 of file LowerXMR.cpp.
resolveReference()
LogicalResult LowerXMRPass::resolveReference (mlir::TypedValue< RefType > refVal, Type desiredType, Location loc, Operation * insertBefore, Value & out) inline private
Definition at line 339 of file LowerXMR.cpp.
References builder, circt::calyx::direction::get(), and circt::firrtl::lowerType().
resolveReferencePath()
LogicalResult LowerXMRPass::resolveReferencePath (mlir::TypedValue< RefType > refVal, ImplicitLocOpBuilder builder, mlir::FlatSymbolRefAttr & ref, SmallString< 128 > & stringLeaf) inline private
Definition at line 301 of file LowerXMR.cpp.
References builder, and circt::calyx::direction::get().
runOnOperation()
void LowerXMRPass::runOnOperation () inline override private
Definition at line 52 of file LowerXMR.cpp.
References Python.support::connect(), lec::dbgs(), and circt::firrtl::getInnerRefTo().
setPortToRemove()
void LowerXMRPass::setPortToRemove (Operation * op, size_t index, size_t numPorts) inline private
Definition at line 406 of file LowerXMR.cpp.
References size().
Member Data Documentation
circuitNamespace
CircuitNamespace* LowerXMRPass::circuitNamespace private
Definition at line 745 of file LowerXMR.cpp.
dataflowAt
DenseMap<Value, size_t> LowerXMRPass::dataflowAt private
Map of a reference value to an entry into refSendPathList.
Each entry in refSendPathList represents the path to RefSend. The path is required since there can be multiple paths to the RefSend and we need to identify a unique path.
Definition at line 715 of file LowerXMR.cpp.
dataFlowClasses
llvm::EquivalenceClasses<Value, ValueComparator>* LowerXMRPass::dataFlowClasses private
Definition at line 735 of file LowerXMR.cpp.
moduleNamespaces
DenseMap<Operation *, ModuleNamespace> LowerXMRPass::moduleNamespaces private
Cached module namespaces.
Definition at line 708 of file LowerXMR.cpp.
opsToRemove
SmallVector<Operation *> LowerXMRPass::opsToRemove private
RefResolve, RefSend, and Connects involving them that will be removed.
Definition at line 740 of file LowerXMR.cpp.
pathCache
DenseMap<Attribute, hw::HierPathOp> LowerXMRPass::pathCache private
A cache of already created HierPathOps.
This is used to avoid repeatedly creating the same HierPathOp.
Definition at line 749 of file LowerXMR.cpp.
pathInsertPoint
OpBuilder::InsertPoint LowerXMRPass::pathInsertPoint = {} private
The insertion point where the pass inserts HierPathOps.
Definition at line 752 of file LowerXMR.cpp.
refPortsToRemoveMap
DenseMap<Operation *, llvm::BitVector> LowerXMRPass::refPortsToRemoveMap private
Definition at line 737 of file LowerXMR.cpp.
refSendPathList
SmallVector<node> LowerXMRPass::refSendPathList private
Definition at line 725 of file LowerXMR.cpp.
visitedModules
DenseSet<Operation *> LowerXMRPass::visitedModules private
Definition at line 710 of file LowerXMR.cpp.
xmrPathSuffix
DenseMap<size_t, SmallString<128> > LowerXMRPass::xmrPathSuffix private
Record the internal path to an external module or a memory.
Definition at line 743 of file LowerXMR.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp