CIRCT: circt::firrtl::FIRRTLBaseType Class Reference
circt::firrtl::FIRRTLBaseType Class Reference
#include <FIRRTLTypes.h>
Public Member Functions
bool isConst ()
Returns true if this is a 'const' type that can only hold compile-time constant values.
bool isPassive () const
Return true if this is a "passive" type - one that contains no "flip" types recursively within itself.
FIRRTLBaseType getPassiveType ()
Return this type with any flip types recursively removed from itself.
FIRRTLBaseType getConstType (bool isConst)
Return a 'const' or non-'const' version of this type.
FIRRTLBaseType getAllConstDroppedType ()
Return this type with a 'const' modifiers dropped.
FIRRTLBaseType getMaskType ()
Return this type with all ground types replaced with UInt<1>.
FIRRTLBaseType getWidthlessType ()
Return this type with widths of all ground types removed.
int32_t getBitWidthOrSentinel ()
If this is an IntType, AnalogType, or sugar type for a single bit (Clock, Reset, etc) then return the bitwidth.
bool isRegisterType ()
Returns true if this is a non-const "passive" that which is not analog.
bool isResetType ()
Return true if this is a valid "reset" type.
uint64_t getMaxFieldID ()
Get the maximum field ID of this type.
std::pair< circt::hw::FieldIDTypeInterface, uint64_t > getSubTypeByFieldID (uint64_t fieldID)
Get the sub-type of a type for a field ID, and the subfield's ID.
circt::hw::FieldIDTypeInterface getFinalTypeByFieldID (uint64_t fieldID)
Return the final type targeted by this field ID by recursively walking all nested aggregate types.
std::pair< uint64_t, bool > rootChildFieldID (uint64_t fieldID, uint64_t index)
Returns the effective field id when treating the index field as the root of the type.
Static Public Member Functions
static bool classof (Type type)
Support method to enable LLVM-style type casting.
Detailed Description
Definition at line 117 of file FIRRTLTypes.h.
Member Function Documentation
classof()
static bool circt::firrtl::FIRRTLBaseType::classof (Type type) inline static
Support method to enable LLVM-style type casting.
Definition at line 156 of file FIRRTLTypes.h.
getAllConstDroppedType()
FIRRTLBaseType FIRRTLBaseType::getAllConstDroppedType ()
Return this type with a 'const' modifiers dropped.
Definition at line 559 of file FIRRTLTypes.cpp.
References getAllConstDroppedType(), and getConstType().
Referenced by convertType(), and getAllConstDroppedType().
getBitWidthOrSentinel()
int32_t FIRRTLBaseType::getBitWidthOrSentinel ()
If this is an IntType, AnalogType, or sugar type for a single bit (Clock, Reset, etc) then return the bitwidth.
Return -1 if the is one of these types but without a specified bitwidth. Return -2 if this isn't a simple type.
Definition at line 635 of file FIRRTLTypes.cpp.
References circt::firrtl::IntType::getWidthOrSentinel().
Referenced by circt::firrtl::areTypesEquivalent(), connectToLeafs(), circt::firrtl::emitConnect(), inferMuxReturnType(), circt::firrtl::isTypeLarger(), isZeroBitFIRRTLType(), LowerXMRPass::isZeroWidth(), FIRRTLOperandForwarder< OpNum >::match(), ConnectSourceOperandForwarder< OpNum >::match(), FIRRTLOperandForwarder< OpNum >::rewrite(), FIRRTLConstantifier::rewrite(), and tryEliminatingConnectsToValue().
getConstType()
FIRRTLBaseType FIRRTLBaseType::getConstType (bool isConst)
Return a 'const' or non-'const' version of this type.
Definition at line 547 of file FIRRTLTypes.cpp.
References getConstType(), and isConst().
Referenced by circt::firrtl::areTypesConstCastable(), circt::firrtl::areTypesEquivalent(), circt::firrtl::areTypesWeaklyEquivalent(), getAllConstDroppedType(), getConstType(), and updateType().
getFinalTypeByFieldID()
circt::hw::FieldIDTypeInterface FIRRTLBaseType::getFinalTypeByFieldID (uint64_t fieldID)
Return the final type targeted by this field ID by recursively walking all nested aggregate types.
This is the identity function for ground types.
Definition at line 690 of file FIRRTLTypes.cpp.
getMaskType()
FIRRTLBaseType FIRRTLBaseType::getMaskType ()
Return this type with all ground types replaced with UInt<1>.
This is used for mem operations.
Definition at line 573 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get(), and isConst().
getMaxFieldID()
uint64_t FIRRTLBaseType::getMaxFieldID ()
Get the maximum field ID of this type.
For integers and other ground types, there are no subfields and the maximum field ID is 0. For bundle types and vector types, each field is assigned a field ID in a depth-first walk order. This function is used to calculate field IDs when this type is nested under another type.
Definition at line 660 of file FIRRTLTypes.cpp.
References getMaxFieldID().
Referenced by circt::firrtl::detail::BundleTypeStorage::BundleTypeStorage(), circt::firrtl::detail::FEnumTypeStorage::FEnumTypeStorage(), and getMaxFieldID().
getPassiveType()
FIRRTLBaseType FIRRTLBaseType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 534 of file FIRRTLTypes.cpp.
References getPassiveType().
Referenced by getPassiveType(), circt::firrtl::isTypeLarger(), isZeroBitFIRRTLType(), and circt::firrtl::lowerType().
getSubTypeByFieldID()
std::pair< circt::hw::FieldIDTypeInterface, uint64_t > FIRRTLBaseType::getSubTypeByFieldID (uint64_t fieldID)
Get the sub-type of a type for a field ID, and the subfield's ID.
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
Definition at line 673 of file FIRRTLTypes.cpp.
References getSubTypeByFieldID().
Referenced by getSubTypeByFieldID().
getWidthlessType()
FIRRTLBaseType FIRRTLBaseType::getWidthlessType ()
Return this type with widths of all ground types removed.
Remove the widths from this type.
This enables two types to be compared by structure and name ignoring widths.
All widths are replaced with an unknown width.
Definition at line 601 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by circt::firrtl::areTypesEquivalent(), circt::firrtl::areTypesWeaklyEquivalent(), FIRRTLOperandForwarder< OpNum >::match(), and ConnectSourceOperandForwarder< OpNum >::match().
isConst()
bool FIRRTLBaseType::isConst ()
Returns true if this is a 'const' type that can only hold compile-time constant values.
Definition at line 508 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::areTypesConstCastable(), circt::firrtl::IntType::get(), getConstType(), circt::firrtl::IntType::getConstType(), getMaskType(), isConstFieldDriven(), resizeType(), and updateType().
isPassive()
bool circt::firrtl::FIRRTLBaseType::isPassive () const inline
Return true if this is a "passive" type - one that contains no "flip" types recursively within itself.
Definition at line 129 of file FIRRTLTypes.h.
Referenced by circt::firrtl::areTypesConstCastable(), emitPortType(), circt::firrtl::detail::FEnumTypeStorage::FEnumTypeStorage(), isConstFieldDriven(), isRegisterType(), ConnectInvalidator::match(), and tryEliminatingConnectsToValue().
isRegisterType()
bool circt::firrtl::FIRRTLBaseType::isRegisterType () inline
Returns true if this is a non-const "passive" that which is not analog.
Definition at line 162 of file FIRRTLTypes.h.
References circt::firrtl::containsConst(), and isPassive().
isResetType()
bool FIRRTLBaseType::isResetType ()
Return true if this is a valid "reset" type.
Return true if this is a type usable as a reset.
This must be either an abstract reset, a concrete 1-bit UInt, an asynchronous reset, or an uninfered width UInt.
Definition at line 652 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::areTypesEquivalent(), and circt::firrtl::areTypesWeaklyEquivalent().
rootChildFieldID()
std::pair< uint64_t, bool > FIRRTLBaseType::rootChildFieldID (uint64_t fieldID, uint64_t index)
Returns the effective field id when treating the index field as the root of the type.
Essentially maps a fieldID to a fieldID after a subfield op. Returns the new id and whether the id is in the given child.
Definition at line 697 of file FIRRTLTypes.cpp.
References rootChildFieldID().
Referenced by rootChildFieldID().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp