CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.cpp File Reference
CPPAPI.cpp File Reference
#include "CPPAPI.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWDialect.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Format.h"
#include <initializer_list>
#include <string>
Functions
static std::string lowercase (llvm::StringRef str)
static std::string joinStringAttrArray (mlir::ArrayAttr strings, llvm::StringRef delimiter)
static void emitCPPType (Type type, mlir::raw_indented_ostream &os)
static bool isZeroWidthInt (Type type)
Function Documentation
emitCPPType()
static void emitCPPType (Type type, mlir::raw_indented_ostream & os) static
Definition at line 58 of file CPPAPI.cpp.
Referenced by circt::esi::cppapi::CPPType::write().
isZeroWidthInt()
static bool isZeroWidthInt (Type type) static
Definition at line 97 of file CPPAPI.cpp.
Referenced by circt::esi::cppapi::CPPType::write().
joinStringAttrArray()
static std::string joinStringAttrArray (mlir::ArrayAttr strings, llvm::StringRef delimiter) static
Definition at line 48 of file CPPAPI.cpp.
Referenced by circt::esi::cppapi::CPPDesignModule::write().
lowercase()
static std::string lowercase (llvm::StringRef str) static
Definition at line 40 of file CPPAPI.cpp.
Referenced by circt::esi::cppapi::CPPDesignModule::write().