CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/DC/Transforms/DCMaterialization.cpp File Reference
DCMaterialization.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/DC/DCOps.h"
#include "circt/Dialect/DC/DCPasses.h"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::dc
Functions
static void replaceFirstUse (Operation *op, Value oldVal, Value newVal)
static void insertSink (Value val, OpBuilder &rewriter)
static void insertFork (Value result, OpBuilder &rewriter)
static LogicalResult addForkOps (Block &block, OpBuilder &rewriter)
LogicalResult circt::dc::addSinkOps (Block &block, OpBuilder &rewriter)
Function Documentation
addForkOps()
static LogicalResult addForkOps (Block & block, OpBuilder & rewriter) static
Definition at line 54 of file DCMaterialization.cpp.
References insertFork().
insertFork()
static void insertFork (Value result, OpBuilder & rewriter) static
Definition at line 34 of file DCMaterialization.cpp.
References replaceFirstUse().
Referenced by addForkOps(), and addLazyForks().
insertSink()
static void insertSink (Value val, OpBuilder & rewriter) static
Definition at line 29 of file DCMaterialization.cpp.
Referenced by circt::dc::addSinkOps().
replaceFirstUse()
static void replaceFirstUse (Operation * op, Value oldVal, Value newVal) static
Definition at line 21 of file DCMaterialization.cpp.
Referenced by insertFork().