CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/ESI/cosim/dpi.h File Reference
dpi.h File Reference
#include "external/dpi/svdpi.h"
Macros
#define DPI extern "C"
Functions
DPI int sv2cCosimserverEpRegister (char *endpointId, long long sendTypeId, int sendTypeSize, long long recvTypeId, int recvTypeSize)
Register an endpoint.
DPI int sv2cCosimserverEpTryGet (char *endpointId, const svOpenArrayHandle data, unsigned int *sizeBytes)
Try to get a message from a client.
DPI int sv2cCosimserverEpTryPut (char *endpointId, const svOpenArrayHandle data, int dataLimit)
Send a message to a client.
DPI int sv2cCosimserverInit ()
Start the server.
DPI void sv2cCosimserverFinish ()
Shutdown the RPC server.
Macro Definition Documentation
DPI
#define DPI extern "C"
Definition at line 23 of file dpi.h.
Function Documentation
sv2cCosimserverEpRegister()
DPI int sv2cCosimserverEpRegister (char * endpointId, long long sendTypeId, int sendTypeSize, long long recvTypeId, int recvTypeSize)
Register an endpoint.
Definition at line 103 of file DpiEntryPoints.cpp.
References circt::esi::cosim::RpcServer::endpoints, circt::esi::cosim::EndpointRegistry::registerEndpoint(), server, and sv2cCosimserverInit().
sv2cCosimserverEpTryGet()
DPI int sv2cCosimserverEpTryGet (char * endpointId, const svOpenArrayHandle data, unsigned int * sizeBytes)
Try to get a message from a client.
Definition at line 121 of file DpiEntryPoints.cpp.
References circt::esi::cosim::RpcServer::endpoints, circt::esi::cosim::Endpoint::getMessageToSim(), log(), server, svGetArrElemPtr1(), svSizeOfArray(), and validateSvOpenArray().
sv2cCosimserverEpTryPut()
DPI int sv2cCosimserverEpTryPut (char * endpointId, const svOpenArrayHandle data, int dataLimit)
Send a message to a client.
Definition at line 187 of file DpiEntryPoints.cpp.
References circt::esi::cosim::RpcServer::endpoints, log(), circt::esi::cosim::Endpoint::pushMessageToClient(), server, svGetArrElemPtr1(), svSizeOfArray(), and validateSvOpenArray().
sv2cCosimserverFinish()
DPI void sv2cCosimserverFinish ()
Shutdown the RPC server.
Definition at line 226 of file DpiEntryPoints.cpp.
References logFile, server, serverMutex, and circt::esi::cosim::RpcServer::stop().
sv2cCosimserverInit()
DPI int sv2cCosimserverInit ()
Start the server.
Not required as the first endpoint registration will do this. Provided if one wants to start the server early.
Definition at line 240 of file DpiEntryPoints.cpp.
References findPort(), logFile, circt::esi::cosim::RpcServer::run(), server, and serverMutex.
Referenced by sv2cCosimserverEpRegister().