CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/ESIEmitCollateral.cpp File Reference
ESIEmitCollateral.cpp File Reference
#include "../PassDetails.h"
#include "circt/Dialect/ESI/APIUtilities.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/ESI/ESIPasses.h"
#include "circt/Dialect/ESI/ESIServices.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/LLVM.h"
#include "circt/Support/SymCache.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/JSON.h"
Functions
static llvm::json::Value toJSON (Type type)
static llvm::json::Value toJSON (Attribute attr)
Function Documentation
toJSON() [1/2]
static llvm::json::Value toJSON (Attribute attr) static
Definition at line 71 of file ESIEmitCollateral.cpp.
References circt::hw::getBitWidth(), circt::esi::ESIAPIType::name(), toJSON(), and circt::esi::ESIAPIType::typeID().
toJSON() [2/2]
static llvm::json::Value toJSON (Type type) static
Definition at line 35 of file ESIEmitCollateral.cpp.
Referenced by toJSON().