CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/ESILowerPorts.cpp File Reference
ESILowerPorts.cpp File Reference
#include "../PassDetails.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "circt/Support/LLVM.h"
#include "circt/Support/SymCache.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static StringAttr appendToRtlName (StringAttr base, const Twine &suffix)
Return a attribute with the specified suffix appended.
static StringRef getStringAttributeOr (Operation *op, StringRef attrName, StringRef def)
static StringRef getOperandName (Value operand)
static std::string & constructInstanceName (Value operand, sv::InterfaceOp iface, std::string &name)
Create a reasonable name for a SV interface instance.
Function Documentation
appendToRtlName()
static StringAttr appendToRtlName (StringAttr base, const Twine & suffix) static
Return a attribute with the specified suffix appended.
Definition at line 26 of file ESILowerPorts.cpp.
References circt::calyx::direction::get().
constructInstanceName()
static std::string& constructInstanceName (Value operand, sv::InterfaceOp iface, std::string & name) static
Create a reasonable name for a SV interface instance.
Definition at line 814 of file ESILowerPorts.cpp.
References getOperandName().
getOperandName()
static StringRef getOperandName (Value operand) static
Definition at line 797 of file ESILowerPorts.cpp.
References circt::hw::getModuleArgumentName(), and circt::hw::isAnyModule().
Referenced by constructInstanceName().
getStringAttributeOr()
static StringRef getStringAttributeOr (Operation * op, StringRef attrName, StringRef def) inline static
Definition at line 33 of file ESILowerPorts.cpp.