CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/ESIOps.cpp File Reference
ESIOps.cpp File Reference
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/HW/HWOpInterfaces.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/SV/SVTypes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "circt/Dialect/ESI/ESI.cpp.inc"
#include "circt/Dialect/ESI/ESIInterfaces.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
ParseResult parseWrapFIFOType (OpAsmParser &p, Type &dataType, Type &chanInputType)
void printWrapFIFOType (OpAsmPrinter &p, WrapFIFOOp wrap, Type dataType, Type chanType)
static Type getEsiDataType (circt::sv::InterfaceOp iface)
If 'iface' looks like an ESI interface, return the inner data type.
static LogicalResult verifySVInterface (Operation *op, circt::sv::ModportType modportType, ChannelType chanType)
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
static bool parseInferWindowRet (OpAsmParser &p, Type &frame, Type &windowOut)
Determine the input type ('frame') from the return type ('window').
static void printInferWindowRet (OpAsmPrinter &p, Operation *, Type, Type window)
static ServiceDeclOpInterface getServiceDecl (Operation *op, SymbolTableCollection &symbolTable, hw::InnerRefAttr servicePort)
Get the port declaration op for the specified service decl, port name.
static LogicalResult reqPortMatches (Operation *op, hw::InnerRefAttr port, SymbolTableCollection &symbolTable)
Check that the type of a given service request matches the services port type.
std::pair< Type, Type > getToServerToClientTypes (RequestInOutChannelOp req)
Overloads to get the two types from a number of supported ops.
std::pair< Type, Type > getToServerToClientTypes (RequestToClientConnectionOp req)
std::pair< Type, Type > getToServerToClientTypes (RequestToServerConnectionOp req)
template<class OpType >
LogicalResult validateRequest (ServiceDeclOpInterface svc, OpType req)
Validate a connection request against a service decl by comparing against the port list.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 592 of file ESIOps.cpp.
Function Documentation
getEsiDataType()
static Type getEsiDataType (circt::sv::InterfaceOp iface) static
If 'iface' looks like an ESI interface, return the inner data type.
Definition at line 244 of file ESIOps.cpp.
Referenced by verifySVInterface().
getServiceDecl()
static ServiceDeclOpInterface getServiceDecl (Operation * op, SymbolTableCollection & symbolTable, hw::InnerRefAttr servicePort) static
Get the port declaration op for the specified service decl, port name.
Definition at line 338 of file ESIOps.cpp.
Referenced by reqPortMatches().
getToServerToClientTypes() [1/3]
std::pair<Type, Type> getToServerToClientTypes (RequestInOutChannelOp req)
Overloads to get the two types from a number of supported ops.
Definition at line 375 of file ESIOps.cpp.
Referenced by validateRequest().
getToServerToClientTypes() [2/3]
std::pair<Type, Type> getToServerToClientTypes (RequestToClientConnectionOp req)
Definition at line 380 of file ESIOps.cpp.
getToServerToClientTypes() [3/3]
std::pair<Type, Type> getToServerToClientTypes (RequestToServerConnectionOp req)
Definition at line 384 of file ESIOps.cpp.
parseInferWindowRet()
static bool parseInferWindowRet (OpAsmParser & p, Type & frame, Type & windowOut) static
Determine the input type ('frame') from the return type ('window').
Definition at line 319 of file ESIOps.cpp.
parseWrapFIFOType()
ParseResult parseWrapFIFOType (OpAsmParser & p, Type & dataType, Type & chanInputType)
Definition at line 197 of file ESIOps.cpp.
printInferWindowRet()
static void printInferWindowRet (OpAsmPrinter & p, Operation * , Type , Type window) static
Definition at line 328 of file ESIOps.cpp.
printWrapFIFOType()
void printWrapFIFOType (OpAsmPrinter & p, WrapFIFOOp wrap, Type dataType, Type chanType)
Definition at line 210 of file ESIOps.cpp.
reqPortMatches()
static LogicalResult reqPortMatches (Operation * op, hw::InnerRefAttr port, SymbolTableCollection & symbolTable) static
Check that the type of a given service request matches the services port type.
Definition at line 350 of file ESIOps.cpp.
References getServiceDecl().
validateRequest()
template<class OpType > LogicalResult validateRequest (ServiceDeclOpInterface svc, OpType req)
Validate a connection request against a service decl by comparing against the port list.
Definition at line 391 of file ESIOps.cpp.
References circt::calyx::direction::get(), getToServerToClientTypes(), circt::esi::ServicePortInfo::name, circt::esi::ServicePortInfo::toClientType, and circt::esi::ServicePortInfo::toServerType.
Referenced by circt::esi::validateServiceConnectionRequest().
verifySVInterface()
static LogicalResult verifySVInterface (Operation * op, circt::sv::ModportType modportType, ChannelType chanType) static
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
Definition at line 259 of file ESIOps.cpp.
References getEsiDataType().