CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportChiselInterface/ExportChiselInterface.cpp File Reference
ExportChiselInterface.cpp File Reference
#include "circt/Conversion/ExportChiselInterface.h"
#include "../PassDetail.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Support/Version.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/ToolOutputFile.h"
Macros
#define DEBUG_TYPE "export-chisel-package"
Functions
static LogicalResult emitPortType (Location location, FIRRTLBaseType type, Direction direction, llvm::raw_ostream &os, unsigned int indent, bool hasEmittedDirection=false)
Emits type construction expression for the port type, recursing into aggregate types as needed.
static LogicalResult emitPort (const PortInfo &port, llvm::raw_ostream &os)
Emits an IO for the port.
static LogicalResult emitModule (FModuleLike module, llvm::raw_ostream &os)
Emits an ExtModule class with port declarations for module.
static LogicalResult exportChiselInterface (CircuitOp circuit, llvm::raw_ostream &os)
Exports a Chisel interface to the output stream.
static LogicalResult exportSplitChiselInterface (CircuitOp circuit, StringRef outputDirectory)
Exports Chisel interface files for the circuit to the specified directory.
Variables
static const unsigned int indentIncrement = 2
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "export-chisel-package"
Definition at line 25 of file ExportChiselInterface.cpp.
Function Documentation
emitModule()
static LogicalResult emitModule (FModuleLike module, llvm::raw_ostream & os) static
Emits an ExtModule class with port declarations for module.
Definition at line 163 of file ExportChiselInterface.cpp.
References emitPort().
Referenced by exportChiselInterface().
emitPort()
static LogicalResult emitPort (const PortInfo & port, llvm::raw_ostream & os) static
Emits an IO for the port.
Definition at line 152 of file ExportChiselInterface.cpp.
References circt::firrtl::PortInfo::direction, emitPortType(), circt::firrtl::PortInfo::getName(), indentIncrement, circt::firrtl::PortInfo::loc, and circt::firrtl::PortInfo::type.
Referenced by emitModule().
emitPortType()
static LogicalResult emitPortType (Location location, FIRRTLBaseType type, Direction direction, llvm::raw_ostream & os, unsigned int indent, bool hasEmittedDirection = false) static
Emits type construction expression for the port type, recursing into aggregate types as needed.
Definition at line 35 of file ExportChiselInterface.cpp.
References circt::firrtl::In, indentIncrement, circt::firrtl::FIRRTLBaseType::isPassive(), and circt::firrtl::Out.
Referenced by emitPort().
exportChiselInterface()
static LogicalResult exportChiselInterface (CircuitOp circuit, llvm::raw_ostream & os) static
Exports a Chisel interface to the output stream.
Definition at line 177 of file ExportChiselInterface.cpp.
References emitModule(), and circt::getCirctVersionComment().
Referenced by exportSplitChiselInterface().
exportSplitChiselInterface()
static LogicalResult exportSplitChiselInterface (CircuitOp circuit, StringRef outputDirectory) static
Exports Chisel interface files for the circuit to the specified directory.
Definition at line 193 of file ExportChiselInterface.cpp.
References exportChiselInterface().
Variable Documentation
indentIncrement
const unsigned int indentIncrement = 2 static
Definition at line 31 of file ExportChiselInterface.cpp.
Referenced by emitPort(), and emitPortType().