CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLOps.cpp File Reference
FIRRTLOps.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Support/CustomDirectiveImpl.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "circt/Dialect/FIRRTL/FIRRTL.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
template<typename T >
static SmallVector< T > removeElementsAtIndices (ArrayRef< T > input, const llvm::BitVector &indicesToDrop)
Remove elements from the input array corresponding to set bits in indicesToDrop, returning the elements not mentioned.
template<typename RetTy = FIRRTLType, typename... Args>
static RetTy emitInferRetTypeError (std::optional< Location > loc, const Twine &message, Args &&...args)
Emit an error if optional location is non-null, return null of return type.
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type)
Return the kind of port this is given the port type from a 'mem' decl.
void getAsmBlockArgumentNamesImpl (Operation *op, mlir::Region &region, OpAsmSetValueNameFn setNameFn)
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
static ParseResult parseNameKind (OpAsmParser &parser, firrtl::NameKindEnumAttr &result)
A forward declaration for NameKind attribute parser.
static ParseResult parseCircuitOpAttrs (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printCircuitOpAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static SmallVector< PortInfo > getPorts (FModuleLike module)
static void insertPorts (FModuleLike op, ArrayRef< std::pair< unsigned, PortInfo >> ports)
Inserts the given ports.
static void erasePorts (FModuleLike op, const llvm::BitVector &portIndices)
Erases the ports that have their corresponding bit set in portIndices.
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations)
static bool printModulePorts (OpAsmPrinter &p, Block *block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms, ArrayRef< Attribute > portLocs)
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
static ParseResult parseModulePorts (OpAsmParser &parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::Argument > &entryArgs, SmallVectorImpl< Direction > &portDirections, SmallVectorImpl< Attribute > &portNames, SmallVectorImpl< Attribute > &portTypes, SmallVectorImpl< Attribute > &portAnnotations, SmallVectorImpl< Attribute > &portSyms, SmallVectorImpl< Attribute > &portLocs)
Parse a list of module ports.
static void printParameterList (ArrayAttr parameters, OpAsmPrinter &p)
Print a paramter list for a module or instance.
static void printFModuleLikeOp (OpAsmPrinter &p, FModuleLike op)
static ParseResult parseOptionalParameters (OpAsmParser &parser, SmallVectorImpl< Attribute > &parameters)
Parse an parameter list if present.
static ParseResult parseFModuleLikeOp (OpAsmParser &parser, OperationState &result, bool hasSSAIdentifiers)
static void forceableAsmResultNames (Forceable op, StringRef name, OpAsmSetValueNameFn setNameFn)
Helper for naming forceable declarations (and their optional ref result).
static LogicalResult checkConnectFlow (Operation *connect)
Check if the source and sink are of appropriate flow.
static bool isConstFieldDriven (FIRRTLBaseType type, bool isFlip=false, bool outerTypeIsConst=false)
Checks if the type has any 'const' leaf elements .
static LogicalResult checkConnectConditionality (FConnectLike connect)
Checks that connections to 'const' destinations are not dependent on non-'const' conditions in when blocks.
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name)
Get an attribute by name from a list of named attributes.
static bool checkAggConstant (Operation *op, Attribute attr, FIRRTLBaseType type)
template<typename OpTy >
ParseResult parseSubfieldLikeOp (OpAsmParser &parser, OperationState &result)
template<typename OpTy >
static void printSubfieldLikeOp (OpTy op, ::mlir::OpAsmPrinter &printer)
template<typename OpTy >
static LogicalResult verifySubfieldLike (OpTy op)
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t &lhsWidth, int32_t &rhsWidth, std::optional< Location > loc)
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
static FIRRTLBaseType inferMuxReturnType (FIRRTLBaseType high, FIRRTLBaseType low, std::optional< Location > loc)
Infer the result type for a multiplexer given its two operand types, which may be aggregates.
static ParseResult parseElideAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
static void printElideAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseElidePortAnnotations (OpAsmParser &parser, NamedAttrList &resultAttrs)
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
static void printElidePortAnnotations (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static void printNameKind (OpAsmPrinter &p, Operation *op, firrtl::NameKindEnumAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parseFIRRTLImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printFIRRTLImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attrs)
static ParseResult parseMemOp (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printMemOp (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
static ParseResult parseElideEmptyName (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printElideEmptyName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr, ArrayRef< StringRef > extraElides={})
static ParseResult parsePrintfAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printPrintfAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseStopAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printStopAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static ParseResult parseVerifAttrs (OpAsmParser &p, NamedAttrList &resultAttrs)
static void printVerifAttrs (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
static void genericAsmResultNames (Operation *op, OpAsmSetValueNameFn setNameFn)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4598 of file FIRRTLOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< PortInfo > ports, ArrayAttr annotations) static
Definition at line 654 of file FIRRTLOps.cpp.
References builder, circt::calyx::direction::get(), and circt::firrtl::direction::packAttribute().
checkAggConstant()
static bool checkAggConstant (Operation * op, Attribute attr, FIRRTLBaseType type) static
Definition at line 2936 of file FIRRTLOps.cpp.
checkConnectConditionality()
static LogicalResult checkConnectConditionality (FConnectLike connect) static
Checks that connections to 'const' destinations are not dependent on non-'const' conditions in when blocks.
Looks up the value's defining op until the defining op is null or a declaration of the value. If a SubAccessOp is encountered with a 'const' input, originalFieldType is made 'const'.
Definition at line 2361 of file FIRRTLOps.cpp.
References Python.support::connect(), and isConstFieldDriven().
checkConnectFlow()
static LogicalResult checkConnectFlow (Operation * connect) static
Check if the source and sink are of appropriate flow.
Definition at line 2300 of file FIRRTLOps.cpp.
References Python.support::connect(), circt::firrtl::foldFlow(), circt::firrtl::getDeclarationKind(), circt::firrtl::getFieldName(), circt::firrtl::getFieldRefFromValue(), circt::firrtl::Instance, circt::firrtl::Port, circt::firrtl::Sink, and circt::firrtl::Source.
emitInferRetTypeError()
template<typename RetTy = FIRRTLType, typename... Args> static RetTy emitInferRetTypeError (std::optional< Location > loc, const Twine & message, Args &&... args) static
Emit an error if optional location is non-null, return null of return type.
Definition at line 90 of file FIRRTLOps.cpp.
erasePorts()
static void erasePorts (FModuleLike op, const llvm::BitVector & portIndices) static
Erases the ports that have their corresponding bit set in portIndices.
Definition at line 566 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::getNumPorts(), circt::firrtl::direction::packAttribute(), removeElementsAtIndices(), and circt::firrtl::direction::unpackAttribute().
forceableAsmResultNames()
static void forceableAsmResultNames (Forceable op, StringRef name, OpAsmSetValueNameFn setNameFn) static
Helper for naming forceable declarations (and their optional ref result).
Definition at line 2208 of file FIRRTLOps.cpp.
genericAsmResultNames()
static void genericAsmResultNames (Operation * op, OpAsmSetValueNameFn setNameFn) static
Definition at line 4329 of file FIRRTLOps.cpp.
getAsmBlockArgumentNamesImpl()
void getAsmBlockArgumentNamesImpl (Operation * op, mlir::Region & region, OpAsmSetValueNameFn setNameFn)
Get a special name to use when printing the entry block arguments of the region contained by an operation in this dialect.
Definition at line 250 of file FIRRTLOps.cpp.
getAttr()
static Attribute getAttr (ArrayRef< NamedAttribute > attrs, StringRef name) static
Get an attribute by name from a list of named attributes.
Same as above, but casts the attribute to a specific type.
Aborts if the attribute does not exist.
Definition at line 2723 of file FIRRTLOps.cpp.
getMemPortKindFromType()
static MemOp::PortKind getMemPortKindFromType (FIRRTLType type) static
Return the kind of port this is given the port type from a 'mem' decl.
Definition at line 115 of file FIRRTLOps.cpp.
References circt::firrtl::addr, circt::firrtl::clk, circt::firrtl::data, circt::firrtl::en, circt::firrtl::mask, circt::firrtl::rdata, circt::firrtl::wdata, circt::firrtl::wmask, and circt::firrtl::wmode.
getPorts()
static SmallVector<PortInfo> getPorts (FModuleLike module) static
Definition at line 458 of file FIRRTLOps.cpp.
References circt::firrtl::AnnotationSet::forPort(), and circt::firrtl::getNumPorts().
inferMuxReturnType()
static FIRRTLBaseType inferMuxReturnType (FIRRTLBaseType high, FIRRTLBaseType low, std::optional< Location > loc) static
Infer the result type for a multiplexer given its two operand types, which may be aggregates.
This essentially performs a pairwise comparison of fields and elements, as follows:
Identical operands inferred to their common type
Integer operands inferred to the larger one if both have a known width, a widthless integer otherwise.
Vectors inferred based on the element type.
Bundles inferred in a pairwise fashion based on the field types.
Definition at line 3888 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::FIRRTLBaseType::getBitWidthOrSentinel().
insertPorts()
static void insertPorts (FModuleLike op, ArrayRef< std::pair< unsigned, PortInfo >> ports) static
Inserts the given ports.
The insertion indices are expected to be in order. Insertion occurs in-order, such that ports with the same insertion index appear in the module in the same order they appeared in the list.
Definition at line 493 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::getNumPorts(), circt::firrtl::direction::packAttribute(), and circt::firrtl::direction::unpackAttribute().
isConstFieldDriven()
static bool isConstFieldDriven (FIRRTLBaseType type, bool isFlip = false, bool outerTypeIsConst = false) static
Checks if the type has any 'const' leaf elements .
If isFlip is true, the const leaf is not considered to be driven.
Definition at line 2337 of file FIRRTLOps.cpp.
References circt::firrtl::FIRRTLBaseType::isConst(), and circt::firrtl::FIRRTLBaseType::isPassive().
Referenced by checkConnectConditionality().
isSameIntTypeKind()
static bool isSameIntTypeKind (Type lhs, Type rhs, int32_t & lhsWidth, int32_t & rhsWidth, std::optional< Location > loc) static
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
If unknown, return -1 for the widths.
On failure, this reports and error and returns false. This function should not be used if you don't want an error reported.
Definition at line 3508 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::getWidthOrSentinel(), and circt::firrtl::IntType::isSigned().
Referenced by circt::firrtl::impl::inferAddSubResult(), circt::firrtl::impl::inferBitwiseResult(), and circt::firrtl::impl::verifySameOperandsIntTypeKind().
parseCircuitOpAttrs()
static ParseResult parseCircuitOpAttrs (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 300 of file FIRRTLOps.cpp.
parseElideAnnotations()
static ParseResult parseElideAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding an empty 'annotations' attribute if not specified.
Definition at line 4162 of file FIRRTLOps.cpp.
Referenced by parseElidePortAnnotations(), and parseFIRRTLImplicitSSAName().
parseElideEmptyName()
static ParseResult parseElideEmptyName (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 4278 of file FIRRTLOps.cpp.
Referenced by parsePrintfAttrs(), parseStopAttrs(), and parseVerifAttrs().
parseElidePortAnnotations()
static ParseResult parseElidePortAnnotations (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Parse an optional attribute dictionary, adding empty 'annotations' and 'portAnnotations' attributes if not specified.
Definition at line 4186 of file FIRRTLOps.cpp.
References parseElideAnnotations().
Referenced by parseMemOp().
parseFIRRTLImplicitSSAName()
static ParseResult parseFIRRTLImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 4243 of file FIRRTLOps.cpp.
References circt::inferImplicitSSAName(), and parseElideAnnotations().
parseFModuleLikeOp()
static ParseResult parseFModuleLikeOp (OpAsmParser & parser, OperationState & result, bool hasSSAIdentifiers) static
Definition at line 1077 of file FIRRTLOps.cpp.
parseMemOp()
static ParseResult parseMemOp (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 4264 of file FIRRTLOps.cpp.
References parseElidePortAnnotations().
parseModulePorts()
static ParseResult parseModulePorts (OpAsmParser & parser, bool hasSSAIdentifiers, SmallVectorImpl< OpAsmParser::Argument > & entryArgs, SmallVectorImpl< Direction > & portDirections, SmallVectorImpl< Attribute > & portNames, SmallVectorImpl< Attribute > & portTypes, SmallVectorImpl< Attribute > & portAnnotations, SmallVectorImpl< Attribute > & portSyms, SmallVectorImpl< Attribute > & portLocs) static
Parse a list of module ports.
If port names are SSA identifiers, then this will populate entryArgs.
Definition at line 859 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::hw::InnerSymbolTable::getInnerSymbolAttrName(), circt::firrtl::In, isdigit, and circt::firrtl::Out.
parseNameKind()
static ParseResult parseNameKind (OpAsmParser & parser, firrtl::NameKindEnumAttr & result) static
A forward declaration for NameKind attribute parser.
Definition at line 4215 of file FIRRTLOps.cpp.
References circt::calyx::direction::get().
parseOptionalParameters()
static ParseResult parseOptionalParameters (OpAsmParser & parser, SmallVectorImpl< Attribute > & parameters) static
Parse an parameter list if present.
module-parameter-list ::= < parameter-decl (, parameter-decl)* > parameter-decl ::= identifier : type parameter-decl ::= identifier : type = attribute
Definition at line 1052 of file FIRRTLOps.cpp.
parsePrintfAttrs()
static ParseResult parsePrintfAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 4297 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseStopAttrs()
static ParseResult parseStopAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 4307 of file FIRRTLOps.cpp.
References parseElideEmptyName().
parseSubfieldLikeOp()
template<typename OpTy > ParseResult parseSubfieldLikeOp (OpAsmParser & parser, OperationState & result)
Definition at line 3147 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::impl::inferReturnTypes().
parseVerifAttrs()
static ParseResult parseVerifAttrs (OpAsmParser & p, NamedAttrList & resultAttrs) static
Definition at line 4316 of file FIRRTLOps.cpp.
References parseElideEmptyName().
printCircuitOpAttrs()
static void printCircuitOpAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 309 of file FIRRTLOps.cpp.
printElideAnnotations()
static void printElideAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 4171 of file FIRRTLOps.cpp.
Referenced by printFIRRTLImplicitSSAName().
printElideEmptyName()
static void printElideEmptyName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 4287 of file FIRRTLOps.cpp.
Referenced by printPrintfAttrs(), printStopAttrs(), and printVerifAttrs().
printElidePortAnnotations()
static void printElidePortAnnotations (OpAsmPrinter & p, Operation * op, DictionaryAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 4200 of file FIRRTLOps.cpp.
Referenced by printMemOp().
printFIRRTLImplicitSSAName()
static void printFIRRTLImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attrs) static
Definition at line 4251 of file FIRRTLOps.cpp.
References circt::elideImplicitSSAName(), circt::hw::InnerName::getInnerNameAttrName(), and printElideAnnotations().
printFModuleLikeOp()
static void printFModuleLikeOp (OpAsmPrinter & p, FModuleLike op) static
Definition at line 974 of file FIRRTLOps.cpp.
printMemOp()
static void printMemOp (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Always elide "ruw" and elide "annotations" if it exists or if it is empty.
Definition at line 4269 of file FIRRTLOps.cpp.
References printElidePortAnnotations().
printModulePorts()
static bool printModulePorts (OpAsmPrinter & p, Block * block, ArrayRef< Direction > portDirections, ArrayRef< Attribute > portNames, ArrayRef< Attribute > portTypes, ArrayRef< Attribute > portAnnotations, ArrayRef< Attribute > portSyms, ArrayRef< Attribute > portLocs) static
Print a list of module ports in the following form: in x: !firrtl.uint<1> [{class = "DontTouch}], out "_port": !firrtl.uint<2>
When there is no block specified, the port names print as MLIR identifiers, wrapping in quotes if not legal to print as-is. When there is no block specified, this function always return false, indicating that there was no issue printing port names.
If there is a block specified, then port names will be printed as SSA values. If there is a reason the printed SSA values can't match the true port name, then this function will return true. When this happens, the caller should print the port names as a part of the attr-dict.
Definition at line 782 of file FIRRTLOps.cpp.
printNameKind()
static void printNameKind (OpAsmPrinter & p, Operation * op, firrtl::NameKindEnumAttr attr, ArrayRef< StringRef > extraElides = {}) static
Definition at line 4232 of file FIRRTLOps.cpp.
printParameterList()
static void printParameterList (ArrayAttr parameters, OpAsmPrinter & p) static
Print a paramter list for a module or instance.
Definition at line 958 of file FIRRTLOps.cpp.
printPrintfAttrs()
static void printPrintfAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 4302 of file FIRRTLOps.cpp.
References printElideEmptyName().
printStopAttrs()
static void printStopAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 4311 of file FIRRTLOps.cpp.
References printElideEmptyName().
printSubfieldLikeOp()
template<typename OpTy > static void printSubfieldLikeOp (OpTy op, ::mlir::OpAsmPrinter & printer) static
Definition at line 3237 of file FIRRTLOps.cpp.
printVerifAttrs()
static void printVerifAttrs (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 4320 of file FIRRTLOps.cpp.
References printElideEmptyName().
removeElementsAtIndices()
template<typename T > static SmallVector<T> removeElementsAtIndices (ArrayRef< T > input, const llvm::BitVector & indicesToDrop) static
Remove elements from the input array corresponding to set bits in indicesToDrop, returning the elements not mentioned.
Definition at line 51 of file FIRRTLOps.cpp.
Referenced by erasePorts().
verifySubfieldLike()
template<typename OpTy > static LogicalResult verifySubfieldLike (OpTy op) static
Definition at line 3264 of file FIRRTLOps.cpp.