CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/HWArithToHW/HWArithToHW.cpp File Reference
HWArithToHW.cpp File Reference
#include "circt/Conversion/HWArithToHW.h"
#include "../PassDetail.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HWArith/HWArithOps.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/ConversionPatterns.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/TypeSwitch.h"
Macros
#define _CREATE_HWARITH_ICMP_CASE(x)
Functions
static void improveNamehint (Value oldValue, Operation *newOp, llvm::function_ref< std::string(StringRef)> namehintCallback)
static Value extractBits (OpBuilder &builder, Location loc, Value value, unsigned startBit, unsigned bitWidth)
static Value extendTypeWidth (OpBuilder &builder, Location loc, Value value, unsigned targetWidth, bool signExtension)
static bool isSignednessType (Type type)
static bool isSignednessAttr (Attribute attr)
static bool isLegalOp (Operation *op)
Returns true if the given op is considered as legal for HWArith conversion.
Macro Definition Documentation
_CREATE_HWARITH_ICMP_CASE
#define _CREATE_HWARITH_ICMP_CASE (x)
Value:
  case ICmpPredicate::x:                                                       \
    return isSigned ? comb::ICmpPredicate::s##x : comb::ICmpPredicate::u##x
Function Documentation
extendTypeWidth()
static Value extendTypeWidth (OpBuilder & builder, Location loc, Value value, unsigned targetWidth, bool signExtension) static
Definition at line 71 of file HWArithToHW.cpp.
References builder, extractBits(), and improveNamehint().
extractBits()
static Value extractBits (OpBuilder & builder, Location loc, Value value, unsigned startBit, unsigned bitWidth) static
Definition at line 52 of file HWArithToHW.cpp.
References builder, and improveNamehint().
Referenced by extendTypeWidth().
improveNamehint()
static void improveNamehint (Value oldValue, Operation * newOp, llvm::function_ref< std::string(StringRef)> namehintCallback) static
Definition at line 39 of file HWArithToHW.cpp.
References circt::calyx::direction::get().
Referenced by extendTypeWidth(), and extractBits().
isLegalOp()
static bool isLegalOp (Operation * op) static
Returns true if the given op is considered as legal for HWArith conversion.
Definition at line 133 of file HWArithToHW.cpp.
References isSignednessAttr(), and isSignednessType().
isSignednessAttr()
static bool isSignednessAttr (Attribute attr) static
Definition at line 125 of file HWArithToHW.cpp.
References isSignednessType().
Referenced by isLegalOp().
isSignednessType()
static bool isSignednessType (Type type) static
Definition at line 107 of file HWArithToHW.cpp.
Referenced by isLegalOp(), and isSignednessAttr().