CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp File Reference
HWExportModuleHierarchy.cpp File Reference
#include "PassDetail.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVPasses.h"
#include "circt/Support/Path.h"
#include "mlir/IR/Builders.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/ToolOutputFile.h"
Classes
struct HWExportModuleHierarchyPass
Functions
static void printHierarchy (hw::InstanceOp &inst, SymbolTable &symbolTable, llvm::json::OStream &j)
Recursively print the module hierarchy as serialized as JSON.
static void extractHierarchyFromTop (hw::HWModuleOp op, SymbolTable &symbolTable, llvm::raw_ostream &os)
Return the JSON-serialized module hierarchy for the given module as the top of the hierarchy.
Function Documentation
extractHierarchyFromTop()
static void extractHierarchyFromTop (hw::HWModuleOp op, SymbolTable & symbolTable, llvm::raw_ostream & os) static
Return the JSON-serialized module hierarchy for the given module as the top of the hierarchy.
Definition at line 64 of file HWExportModuleHierarchy.cpp.
References circt::hw::getVerilogModuleName().
Referenced by HWExportModuleHierarchyPass::runOnOperation().
printHierarchy()
static void printHierarchy (hw::InstanceOp & inst, SymbolTable & symbolTable, llvm::json::OStream & j) static
Recursively print the module hierarchy as serialized as JSON.
Definition at line 43 of file HWExportModuleHierarchy.cpp.
References circt::hw::getVerilogModuleName().