CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/InferWidths.cpp File Reference
InferWidths.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/FieldRef.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/GraphTraits.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
Classes
struct llvm::DenseMapInfo< InternedSlot< T > >
Namespaces
mlir
llvm
Macros
#define DEBUG_TYPE "infer-widths"
#define EXPR_NAMES(x) Root##x, Var##x, Derived##x, Id##x, Known##x, Add##x, Pow##x, Max##x, Min##x
#define EXPR_KINDS EXPR_NAMES()
#define EXPR_CLASSES EXPR_NAMES(Expr)
Typedefs
using ExprSolution = std::pair< std::optional< int32_t >, bool >
Functions
static void diagnoseUninferredType (InFlightDiagnostic &diag, Type t, Twine str)
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0>
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const T &e)
Allow rvalue refs to Expr and subclasses to be printed to streams.
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0>
llvm::hash_code mlir::hash_value (const T &e)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const LinIneq &l)
static ExprSolution computeUnary (ExprSolution arg, llvm::function_ref< int32_t(int32_t)> operation)
static ExprSolution computeBinary (ExprSolution lhs, ExprSolution rhs, llvm::function_ref< int32_t(int32_t, int32_t)> operation)
static ExprSolution solveExpr (Expr *expr, SmallPtrSetImpl< Expr * > &seenVars, unsigned indent=1)
Compute the value of a constraint expr.
static bool hasUninferredWidth (Type type)
Check if a type contains any FIRRTL type with uninferred widths.
static FIRRTLBaseType resizeType (FIRRTLBaseType type, uint32_t newWidth)
Resize a uint, sint, or analog type to a specific width.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "infer-widths"
Definition at line 31 of file InferWidths.cpp.
EXPR_CLASSES
#define EXPR_CLASSES EXPR_NAMES(Expr)
Definition at line 90 of file InferWidths.cpp.
EXPR_KINDS
#define EXPR_KINDS EXPR_NAMES()
Definition at line 89 of file InferWidths.cpp.
EXPR_NAMES
#define EXPR_NAMES (x) Root##x, Var##x, Derived##x, Id##x, Known##x, Add##x, Pow##x, Max##x, Min##x
Definition at line 87 of file InferWidths.cpp.
Typedef Documentation
ExprSolution
using ExprSolution = std::pair<std::optional<int32_t>, bool>
Definition at line 797 of file InferWidths.cpp.
Function Documentation
computeBinary()
static ExprSolution computeBinary (ExprSolution lhs, ExprSolution rhs, llvm::function_ref< int32_t(int32_t, int32_t)> operation) static
Definition at line 807 of file InferWidths.cpp.
Referenced by solveExpr().
computeUnary()
static ExprSolution computeUnary (ExprSolution arg, llvm::function_ref< int32_t(int32_t)> operation) static
Definition at line 800 of file InferWidths.cpp.
Referenced by solveExpr().
diagnoseUninferredType()
static void diagnoseUninferredType (InFlightDiagnostic & diag, Type t, Twine str) static
Definition at line 43 of file InferWidths.cpp.
hasUninferredWidth()
static bool hasUninferredWidth (Type type) static
Check if a type contains any FIRRTL type with uninferred widths.
Definition at line 1196 of file InferWidths.cpp.
operator<<() [1/2]
llvm::raw_ostream& operator<< (llvm::raw_ostream & os, const LinIneq & l) inline
Definition at line 694 of file InferWidths.cpp.
operator<<() [2/2]
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0> llvm::raw_ostream& operator<< (llvm::raw_ostream & os, const T & e) inline
Allow rvalue refs to Expr and subclasses to be printed to streams.
Definition at line 72 of file InferWidths.cpp.
resizeType()
static FIRRTLBaseType resizeType (FIRRTLBaseType type, uint32_t newWidth) static
Resize a uint, sint, or analog type to a specific width.
Definition at line 2051 of file InferWidths.cpp.
References circt::calyx::direction::get(), and circt::firrtl::FIRRTLBaseType::isConst().
solveExpr()
static ExprSolution solveExpr (Expr * expr, SmallPtrSetImpl< Expr * > & seenVars, unsigned indent = 1) static
Compute the value of a constraint expr.
seenVars is used as a recursion breaker. Recursive variables are treated as zero. Returns the computed value and a boolean indicating whether a recursion was detected. This may be used to memoize the result of expressions in case they were not involved in a cycle (which may alter their value from the perspective of a variable).
Definition at line 824 of file InferWidths.cpp.
References computeBinary(), computeUnary(), and lec::dbgs().