CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp File Reference
LowerArcToLLVM.cpp File Reference
#include "../PassDetail.h"
#include "circt/Conversion/ArcToLLVM.h"
#include "circt/Conversion/CombToLLVM.h"
#include "circt/Conversion/HWToLLVM.h"
#include "circt/Dialect/Arc/ArcOps.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Support/Namespace.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/SCFToControlFlow/SCFToControlFlow.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "arc-lower-to-llvm"
Functions
static bool isArcType (Type type)
static bool hasArcType (TypeRange types)
static bool hasArcType (ValueRange values)
template<typename Op >
static void addGenericLegality (ConversionTarget &target)
static void populateLegality (ConversionTarget &target)
static void populateTypeConversion (TypeConverter &typeConverter)
static void populateOpConversion (RewritePatternSet &patterns, TypeConverter &typeConverter)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-lower-to-llvm"
Definition at line 30 of file LowerArcToLLVM.cpp.
Function Documentation
addGenericLegality()
template<typename Op > static void addGenericLegality (ConversionTarget & target) static
Definition at line 356 of file LowerArcToLLVM.cpp.
References hasArcType().
hasArcType() [1/2]
static bool hasArcType (TypeRange types) static
Definition at line 347 of file LowerArcToLLVM.cpp.
References isArcType().
Referenced by addGenericLegality(), hasArcType(), and populateLegality().
hasArcType() [2/2]
static bool hasArcType (ValueRange values) static
Definition at line 351 of file LowerArcToLLVM.cpp.
References hasArcType().
isArcType()
static bool isArcType (Type type) static
Definition at line 342 of file LowerArcToLLVM.cpp.
Referenced by hasArcType().
populateLegality()
static void populateLegality (ConversionTarget & target) static
Definition at line 362 of file LowerArcToLLVM.cpp.
References hasArcType().
populateOpConversion()
static void populateOpConversion (RewritePatternSet & patterns, TypeConverter & typeConverter) static
Definition at line 403 of file LowerArcToLLVM.cpp.
populateTypeConversion()
static void populateTypeConversion (TypeConverter & typeConverter) static
Definition at line 387 of file LowerArcToLLVM.cpp.
References circt::calyx::direction::get().