CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp File Reference
LowerAnnotations.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/SV/SVAttributes.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "lower-annos"
Functions
static ArrayAttr getAnnotationsFrom (Operation *op)
Get annotations or an empty set of annotations.
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a)
Construct the annotation array with a new thing appended.
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal)
Update an ArrayAttribute by replacing one entry.
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno)
Apply a new annotation to a resolved target.
static FlatSymbolRefAttr buildNLA (const AnnoPathValue &target, ApplyState &state)
Make an anchor for a non-local annotation.
static FlatSymbolRefAttr scatterNonLocalPath (const AnnoPathValue &target, ApplyState &state)
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
static std::optional< AnnoPathValue > noResolve (DictionaryAttr anno, ApplyState &state)
Always resolve to the circuit, ignoring the annotation.
static std::optional< AnnoPathValue > stdResolveImpl (StringRef rawPath, ApplyState &state)
Implementation of standard resolution.
static std::optional< AnnoPathValue > stdResolve (DictionaryAttr anno, ApplyState &state)
(SFC) FIRRTL SingleTargetAnnotation resolver.
static std::optional< AnnoPathValue > tryResolve (DictionaryAttr anno, ApplyState &state)
Resolves with target, if it exists. If not, resolves to the circuit.
static LogicalResult applyWithoutTargetImpl (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state, bool allowNonLocal)
An applier which puts the annotation on the target and drops the 'target' field from the annotation.
template<bool allowNonLocal, bool allowPortAnnoTarget, typename T , typename... Tr>
static LogicalResult applyWithoutTarget (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
An applier which puts the annotation on the target and drops the 'target' field from the annotation.
template<bool allowNonLocal, typename T , typename... Tr>
static LogicalResult applyWithoutTarget (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
template<bool allowNonLocal = false>
static LogicalResult applyWithoutTarget (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
static LogicalResult drop (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
Just drop the annotation.
static LogicalResult applyDUTAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
static std::optional< Convention > parseConvention (llvm::StringRef str)
static LogicalResult applyConventionAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
static LogicalResult applyAttributeAnnotation (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
template<bool isInline>
static LogicalResult applyLoadMemoryAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
Update a memory op with attributes about memory file loading.
static const AnnoRecord * getAnnotationHandler (StringRef annoStr, bool ignoreUnhandledAnno)
Lookup a record for a given annotation class.
Variables
static const llvm::StringMap< AnnoRecord > annotationRecords
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-annos"
Definition at line 36 of file LowerAnnotations.cpp.
Function Documentation
addAnnotation()
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno) static
Apply a new annotation to a resolved target.
This handles ports, aggregates, modules, wires, etc.
Definition at line 68 of file LowerAnnotations.cpp.
References appendArrayAttr(), circt::firrtl::AnnoTarget::cast(), circt::firrtl::AnnoTarget::dyn_cast_or_null(), circt::calyx::direction::get(), circt::firrtl::getAnnotationAttrName(), getAnnotationsFrom(), circt::firrtl::getNumPorts(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::getPortAnnotationAttrName(), circt::firrtl::AnnoTarget::isa(), and replaceArrayAttrElement().
Referenced by applyDUTAnno(), and applyWithoutTargetImpl().
appendArrayAttr()
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a) static
Construct the annotation array with a new thing appended.
Definition at line 50 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
applyAttributeAnnotation()
static LogicalResult applyAttributeAnnotation (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 358 of file LowerAnnotations.cpp.
References circt::sv::addSVAttributes(), circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isLocal(), and circt::firrtl::AnnoPathValue::ref.
applyConventionAnno()
static LogicalResult applyConventionAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 315 of file LowerAnnotations.cpp.
References circt::firrtl::conventionAnnoClass, circt::firrtl::AnnoTarget::dyn_cast(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoPathValue::isLocal(), parseConvention(), and circt::firrtl::AnnoPathValue::ref.
applyDUTAnno()
static LogicalResult applyDUTAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 285 of file LowerAnnotations.cpp.
References addAnnotation(), circt::firrtl::AnnoPathValue::fieldIdx, circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isLocal(), and circt::firrtl::AnnoPathValue::ref.
applyLoadMemoryAnno()
template<bool isInline> static LogicalResult applyLoadMemoryAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Update a memory op with attributes about memory file loading.
Definition at line 389 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoPathValue::isLocal(), circt::firrtl::AnnoPathValue::isOpOfType(), and circt::firrtl::AnnoPathValue::ref.
applyWithoutTarget() [1/3]
template<bool allowNonLocal, bool allowPortAnnoTarget, typename T , typename... Tr> static LogicalResult applyWithoutTarget (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
An applier which puts the annotation on the target and drops the 'target' field from the annotation.
Optionally handles non-local annotations. Ensures the target resolves to an expected type of operation.
Definition at line 245 of file LowerAnnotations.cpp.
References applyWithoutTargetImpl(), circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isOpOfType(), and circt::firrtl::AnnoPathValue::ref.
Referenced by applyWithoutTarget().
applyWithoutTarget() [2/3]
template<bool allowNonLocal, typename T , typename... Tr> static LogicalResult applyWithoutTarget (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 258 of file LowerAnnotations.cpp.
References applyWithoutTarget().
applyWithoutTarget() [3/3]
template<bool allowNonLocal = false> static LogicalResult applyWithoutTarget (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
An applier which puts the annotation on the target and drops the 'target' field from the annotaiton.
Optionally handles non-local annotations.
Definition at line 268 of file LowerAnnotations.cpp.
References applyWithoutTargetImpl().
applyWithoutTargetImpl()
static LogicalResult applyWithoutTargetImpl (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state, bool allowNonLocal) static
An applier which puts the annotation on the target and drops the 'target' field from the annotation.
Optionally handles non-local annotations.
Definition at line 212 of file LowerAnnotations.cpp.
References addAnnotation(), circt::firrtl::AnnoPathValue::fieldIdx, circt::calyx::direction::get(), circt::firrtl::Annotation::getClass(), circt::firrtl::Annotation::getMember(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoPathValue::isLocal(), circt::firrtl::AnnoPathValue::ref, and scatterNonLocalPath().
Referenced by applyWithoutTarget().
buildNLA()
static FlatSymbolRefAttr buildNLA (const AnnoPathValue & target, ApplyState & state) static
Make an anchor for a non-local annotation.
Use the expanded path to build the module and name list in the anchor.
Definition at line 107 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getModule(), circt::firrtl::ApplyState::getNamespace(), circt::firrtl::AnnoPathValue::instances, circt::firrtl::ApplyState::instPathToNLAMap, circt::firrtl::ApplyState::numReusedHierPaths, circt::firrtl::AnnoPathValue::ref, and circt::firrtl::ApplyState::symTbl.
Referenced by scatterNonLocalPath().
drop()
static LogicalResult drop (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Just drop the annotation.
This is intended for Annotations which are known, but can be safely ignored.
Definition at line 276 of file LowerAnnotations.cpp.
getAnnotationHandler()
static const AnnoRecord* getAnnotationHandler (StringRef annoStr, bool ignoreUnhandledAnno) static
Lookup a record for a given annotation class.
Optionally, returns the record for "circuit.missing" if the record doesn't exist.
Definition at line 572 of file LowerAnnotations.cpp.
References annotationRecords.
getAnnotationsFrom()
static ArrayAttr getAnnotationsFrom (Operation * op) static
Get annotations or an empty set of annotations.
Definition at line 43 of file LowerAnnotations.cpp.
References circt::calyx::direction::get(), and circt::firrtl::getAnnotationAttrName().
Referenced by addAnnotation().
noResolve()
static std::optional<AnnoPathValue> noResolve (DictionaryAttr anno, ApplyState & state) static
Always resolve to the circuit, ignoring the annotation.
Definition at line 153 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit.
parseConvention()
static std::optional<Convention> parseConvention (llvm::StringRef str) static
Definition at line 309 of file LowerAnnotations.cpp.
Referenced by applyConventionAnno().
replaceArrayAttrElement()
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal) static
Update an ArrayAttribute by replacing one entry.
Definition at line 59 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
scatterNonLocalPath()
static FlatSymbolRefAttr scatterNonLocalPath (const AnnoPathValue & target, ApplyState & state) static
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
Returns symbol name used to anchor annotations to path.
Definition at line 141 of file LowerAnnotations.cpp.
References buildNLA().
Referenced by applyWithoutTargetImpl().
stdResolve()
static std::optional<AnnoPathValue> stdResolve (DictionaryAttr anno, ApplyState & state) static
(SFC) FIRRTL SingleTargetAnnotation resolver.
Uses the 'target' field of the annotation with standard parsing to resolve the path. This requires 'target' to exist and be normalized (per docs/FIRRTLAnnotations.md).
Definition at line 179 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, and stdResolveImpl().
stdResolveImpl()
static std::optional<AnnoPathValue> stdResolveImpl (StringRef rawPath, ApplyState & state) static
Implementation of standard resolution.
First parses the target path, then resolves it.
Definition at line 160 of file LowerAnnotations.cpp.
References circt::firrtl::canonicalizeTarget(), circt::firrtl::ApplyState::circuit, circt::firrtl::resolveEntities(), circt::firrtl::ApplyState::symTbl, circt::firrtl::ApplyState::targetCaches, and circt::firrtl::tokenizePath().
Referenced by stdResolve(), and tryResolve().
tryResolve()
static std::optional<AnnoPathValue> tryResolve (DictionaryAttr anno, ApplyState & state) static
Resolves with target, if it exists. If not, resolves to the circuit.
Definition at line 197 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, and stdResolveImpl().
Variable Documentation
annotationRecords
const llvm::StringMap<AnnoRecord> annotationRecords static
Definition at line 466 of file LowerAnnotations.cpp.
Referenced by getAnnotationHandler(), and circt::firrtl::isAnnoClassLowered().