CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp File Reference
LowerTypes.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/NLATable.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOpInterfaces.h"
#include "circt/Dialect/SV/SVOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Parallel.h"
Macros
#define DEBUG_TYPE "firrtl-lower-types"
Functions
static bool hasZeroBitWidth (FIRRTLType type)
Return true if the type has more than zero bitwidth.
static bool isOneDimVectorType (FIRRTLType type)
Return true if the type is a 1d vector type or ground type.
static bool containsBundleType (FIRRTLType type)
Return true if the type has a bundle type as subtype.
static bool isPreservableAggregateType (Type type, PreserveAggregate::PreserveMode mode)
Return true if we can preserve the type.
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > &fields, PreserveAggregate::PreserveMode mode)
Peel one layer of an aggregate type into its components.
static bool isNotSubAccess (Operation *op)
Return if something is not a normal subaccess.
static SmallVector< Operation * > getSAWritePath (Operation *op)
Look through and collect subfields leading to a subaccess.
static bool isAnnotationSensitiveToFieldID (Annotation anno)
Returns whether the given annotation requires precise tracking of the field ID as it gets replicated across lowered operations.
static Attribute updateAnnotationFieldID (MLIRContext *ctxt, Attribute attr, unsigned fieldID, Type i64ty)
If an annotation on one operation is replicated across multiple IR operations as a result of type lowering, the replicated annotations may want to track which field ID they were applied to.
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder *b, MemOp op, FlatBundleFieldEntry field)
static Value cloneAccess (ImplicitLocOpBuilder *builder, Operation *op, Value rhs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "firrtl-lower-types"
Definition at line 50 of file LowerTypes.cpp.
Function Documentation
cloneAccess()
static Value cloneAccess (ImplicitLocOpBuilder * builder, Operation * op, Value rhs) static
Definition at line 768 of file LowerTypes.cpp.
References builder.
cloneMemWithNewType()
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder * b, MemOp op, FlatBundleFieldEntry field) static
Definition at line 258 of file LowerTypes.cpp.
References circt::calyx::direction::get(), circt::firrtl::Annotation::getDict(), circt::firrtl::Annotation::getFieldID(), circt::firrtl::getInnerSymName(), and circt::firrtl::Annotation::setMember().
containsBundleType()
static bool containsBundleType (FIRRTLType type) static
Return true if the type has a bundle type as subtype.
Definition at line 119 of file LowerTypes.cpp.
Referenced by isPreservableAggregateType().
getSAWritePath()
static SmallVector<Operation *> getSAWritePath (Operation * op) static
Look through and collect subfields leading to a subaccess.
Definition at line 214 of file LowerTypes.cpp.
References isNotSubAccess().
hasZeroBitWidth()
static bool hasZeroBitWidth (FIRRTLType type) static
Return true if the type has more than zero bitwidth.
Definition at line 84 of file LowerTypes.cpp.
References circt::firrtl::getBitWidth().
Referenced by isPreservableAggregateType().
isAnnotationSensitiveToFieldID()
static bool isAnnotationSensitiveToFieldID (Annotation anno) static
Returns whether the given annotation requires precise tracking of the field ID as it gets replicated across lowered operations.
Definition at line 229 of file LowerTypes.cpp.
References circt::firrtl::Annotation::isClass(), and circt::firrtl::signalDriverAnnoClass.
Referenced by updateAnnotationFieldID().
isNotSubAccess()
static bool isNotSubAccess (Operation * op) static
Return if something is not a normal subaccess.
Non-normal includes zero-length vectors and constant indexes (which are really subindexes).
Definition at line 205 of file LowerTypes.cpp.
Referenced by getSAWritePath().
isOneDimVectorType()
static bool isOneDimVectorType (FIRRTLType type) static
Return true if the type is a 1d vector type or ground type.
Definition at line 107 of file LowerTypes.cpp.
Referenced by isPreservableAggregateType().
isPreservableAggregateType()
static bool isPreservableAggregateType (Type type, PreserveAggregate::PreserveMode mode) static
Return true if we can preserve the type.
Definition at line 129 of file LowerTypes.cpp.
References circt::firrtl::PreserveAggregate::All, containsBundleType(), hasZeroBitWidth(), isOneDimVectorType(), circt::firrtl::PreserveAggregate::None, circt::firrtl::PreserveAggregate::OneDimVec, and circt::firrtl::PreserveAggregate::Vec.
Referenced by peelType().
peelType()
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > & fields, PreserveAggregate::PreserveMode mode) static
Peel one layer of an aggregate type into its components.
Type may be complex, but empty, in which case fields is empty, but the return is true.
Definition at line 168 of file LowerTypes.cpp.
References isPreservableAggregateType().
updateAnnotationFieldID()
static Attribute updateAnnotationFieldID (MLIRContext * ctxt, Attribute attr, unsigned fieldID, Type i64ty) static
If an annotation on one operation is replicated across multiple IR operations as a result of type lowering, the replicated annotations may want to track which field ID they were applied to.
This function adds a fieldID to such a replicated operation, if the annotation in question requires it.
Definition at line 237 of file LowerTypes.cpp.
References circt::calyx::direction::get(), circt::firrtl::Annotation::getMember(), and isAnnotationSensitiveToFieldID().