CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp File Reference
LowerIntrinsics.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Debug.h"
Functions
static ParseResult hasNPorts (StringRef name, FModuleLike mod, unsigned n)
static ParseResult namedPort (StringRef name, FModuleLike mod, unsigned n, StringRef portName)
template<typename T >
static ParseResult typedPort (StringRef name, FModuleLike mod, unsigned n)
template<typename T >
static ParseResult sizedPort (StringRef name, FModuleLike mod, unsigned n, int32_t size)
static ParseResult hasNParam (StringRef name, FModuleLike mod, unsigned n)
static ParseResult namedParam (StringRef name, FModuleLike mod, StringRef paramName)
static InstanceGraphNode * lookupInstNode (InstancePathCache &instancePathCache, FModuleLike mod)
static bool lowerCirctSizeof (InstancePathCache &instancePathCache, FModuleLike mod)
static bool lowerCirctIsX (InstancePathCache &instancePathCache, FModuleLike mod)
static bool lowerCirctPlusArgTest (InstancePathCache &instancePathCache, FModuleLike mod)
static bool lowerCirctPlusArgValue (InstancePathCache &instancePathCache, FModuleLike mod)
static bool lowerCirctClockGate (InstancePathCache &instancePathCache, FModuleLike mod)
Variables
std::pair< const char *, std::function< bool(InstancePathCache &, FModuleLike)> > intrinsics []
Function Documentation
hasNParam()
static ParseResult hasNParam (StringRef name, FModuleLike mod, unsigned n) static
Definition at line 91 of file LowerIntrinsics.cpp.
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), and lowerCirctSizeof().
hasNPorts()
static ParseResult hasNPorts (StringRef name, FModuleLike mod, unsigned n) static
Definition at line 40 of file LowerIntrinsics.cpp.
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), and lowerCirctSizeof().
lookupInstNode()
static InstanceGraphNode* lookupInstNode (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 118 of file LowerIntrinsics.cpp.
References circt::hw::InstancePathCache::instanceGraph.
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), and lowerCirctSizeof().
lowerCirctClockGate()
static bool lowerCirctClockGate (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 214 of file LowerIntrinsics.cpp.
References builder, circt::firrtl::en, hasNParam(), hasNPorts(), lookupInstNode(), and namedPort().
lowerCirctIsX()
static bool lowerCirctIsX (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 148 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), lookupInstNode(), namedPort(), and size().
lowerCirctPlusArgTest()
static bool lowerCirctPlusArgTest (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 169 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), lookupInstNode(), namedParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctPlusArgValue()
static bool lowerCirctPlusArgValue (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 190 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), lookupInstNode(), namedParam(), namedPort(), and circt::hw::InstanceGraphNode::uses().
lowerCirctSizeof()
static bool lowerCirctSizeof (InstancePathCache & instancePathCache, FModuleLike mod) static
Definition at line 126 of file LowerIntrinsics.cpp.
References builder, hasNParam(), hasNPorts(), lookupInstNode(), namedPort(), and size().
namedParam()
static ParseResult namedParam (StringRef name, FModuleLike mod, StringRef paramName) static
Definition at line 101 of file LowerIntrinsics.cpp.
Referenced by lowerCirctPlusArgTest(), and lowerCirctPlusArgValue().
namedPort()
static ParseResult namedPort (StringRef name, FModuleLike mod, unsigned n, StringRef portName) static
Definition at line 49 of file LowerIntrinsics.cpp.
References circt::hw::instance_like_impl::getName().
Referenced by lowerCirctClockGate(), lowerCirctIsX(), lowerCirctPlusArgTest(), lowerCirctPlusArgValue(), and lowerCirctSizeof().
sizedPort()
template<typename T > static ParseResult sizedPort (StringRef name, FModuleLike mod, unsigned n, int32_t size) static
Definition at line 79 of file LowerIntrinsics.cpp.
References size().
typedPort()
template<typename T > static ParseResult typedPort (StringRef name, FModuleLike mod, unsigned n) static
Definition at line 65 of file LowerIntrinsics.cpp.
Variable Documentation
intrinsics
std::pair<const char *, std::function<bool(InstancePathCache &, FModuleLike)> > intrinsics[]
Initial value:
= {
        {"circt.sizeof", lowerCirctSizeof},
        {"circt_sizeof", lowerCirctSizeof},
        {"circt.isX", lowerCirctIsX},
        {"circt_isX", lowerCirctIsX},
        {"circt.plusargs.test", lowerCirctPlusArgTest},
        {"circt_plusargs_test", lowerCirctPlusArgTest},
        {"circt.plusargs.value", lowerCirctPlusArgValue},
        {"circt_plusargs_value", lowerCirctPlusArgValue},
        {"circt.clock_gate", lowerCirctClockGate},
        {"circt_clock_gate", lowerCirctClockGate},
}
Definition at line 241 of file LowerIntrinsics.cpp.