CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/MSFT/Transforms/MSFTPartition.cpp File Reference
MSFTPartition.cpp File Reference
#include "MSFTPassCommon.h"
#include "PassDetails.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/MSFT/MSFTDialect.h"
#include "circt/Dialect/MSFT/MSFTOpInterfaces.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/MSFT/MSFTPasses.h"
#include "circt/Support/Namespace.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassRegistry.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Functions
static bool isWireManipulationOp (Operation *op)
Is this operation "free" and copy-able?
static SymbolRefAttr getPart (Operation *op)
static bool isDrivenByPartOpsOnly (Operation *op, const IRMapping &partOps, DenseMap< Operation *, bool > &seen)
Determine if 'op' is driven exclusively by other tagged ops or wires which are themselves exclusively driven by tagged ops.
void copyIntoPart (ArrayRef< Operation * > taggedOps, Block *partBlock, bool extendMaximalUp)
Move the list of tagged operations in to 'partBlock' and copy/move any free (wire) ops connecting them in also.
void copyInto (MSFTModuleOp mod, DenseMap< SymbolRefAttr, Block * > &perPartBlocks, Block *nonLocalBlock)
Move tagged ops into separate blocks.
static StringRef getOpName (Operation *op)
Heuristics to get the entity name.
static void setEntityName (Operation *op, const Twine &name)
Try to set the entity name.
static StringRef getResultName (OpResult res, const SymbolCache &syms, std::string &buff)
Heuristics to get the output name.
static StringRef getOperandName (OpOperand &oper, const SymbolCache &syms, std::string &buff)
Heuristics to get the input name.
static ArrayAttr getGlobalRefs (Operation *op)
Helper to get the circt.globalRef attribute.
Function Documentation
copyInto()
void copyInto (MSFTModuleOp mod, DenseMap< SymbolRefAttr, Block * > & perPartBlocks, Block * nonLocalBlock)
Move tagged ops into separate blocks.
Copy any wire ops connecting them as well.
Definition at line 206 of file MSFTPartition.cpp.
References copyIntoPart(), and getPart().
copyIntoPart()
void copyIntoPart (ArrayRef< Operation * > taggedOps, Block * partBlock, bool extendMaximalUp)
Move the list of tagged operations in to 'partBlock' and copy/move any free (wire) ops connecting them in also.
If 'extendMaximalUp` is specified, attempt to copy all the way up to the block args.
Definition at line 120 of file MSFTPartition.cpp.
References getPart(), isDrivenByPartOpsOnly(), and isWireManipulationOp().
Referenced by copyInto().
getGlobalRefs()
static ArrayAttr getGlobalRefs (Operation * op) static
Helper to get the circt.globalRef attribute.
Definition at line 327 of file MSFTPartition.cpp.
getOperandName()
static StringRef getOperandName (OpOperand & oper, const SymbolCache & syms, std::string & buff) static
Heuristics to get the input name.
Definition at line 300 of file MSFTPartition.cpp.
References circt::SymbolCache::getDefinition(), circt::msft::getModulePortInfo(), and circt::msft::isAnyModule().
getOpName()
static StringRef getOpName (Operation * op) static
Heuristics to get the entity name.
Definition at line 265 of file MSFTPartition.cpp.
getPart()
static SymbolRefAttr getPart (Operation * op) static
Definition at line 39 of file MSFTPartition.cpp.
Referenced by copyInto(), and copyIntoPart().
getResultName()
static StringRef getResultName (OpResult res, const SymbolCache & syms, std::string & buff) static
Heuristics to get the output name.
Definition at line 284 of file MSFTPartition.cpp.
References circt::msft::getValueName().
isDrivenByPartOpsOnly()
static bool isDrivenByPartOpsOnly (Operation * op, const IRMapping & partOps, DenseMap< Operation *, bool > & seen) static
Determine if 'op' is driven exclusively by other tagged ops or wires which are themselves exclusively driven by tagged ops.
Recursive but memoized via seen.
Definition at line 95 of file MSFTPartition.cpp.
References isWireManipulationOp().
Referenced by copyIntoPart().
isWireManipulationOp()
static bool isWireManipulationOp (Operation * op) static
Is this operation "free" and copy-able?
Definition at line 32 of file MSFTPartition.cpp.
Referenced by copyIntoPart(), and isDrivenByPartOpsOnly().
setEntityName()
static void setEntityName (Operation * op, const Twine & name) static
Try to set the entity name.
TODO: this needs to be more complex to deal with renaming symbols.
Definition at line 275 of file MSFTPartition.cpp.
References circt::calyx::direction::get().