CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/MSFT/MSFTOps.cpp File Reference
MSFTOps.cpp File Reference
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/Comb/CombDialect.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/ModuleImplementation.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/MSFT/MSFT.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs)
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, const hw::ModulePortInfo &ports)
static ParseResult parsePhysLoc (OpAsmParser &p, PhysLocationAttr &attr)
static void printPhysLoc (OpAsmPrinter &p, Operation *, PhysLocationAttr loc)
static ParseResult parseListOptionalRegLocList (OpAsmParser &p, LocationVectorAttr &locs)
static void printListOptionalRegLocList (OpAsmPrinter &p, Operation *, LocationVectorAttr locs)
static ParseResult parseImplicitInnerRef (OpAsmParser &p, hw::InnerRefAttr &innerRef)
void printImplicitInnerRef (OpAsmPrinter &p, Operation *, hw::InnerRefAttr innerRef)
static ParseResult parseParameterList (OpAsmParser &parser, SmallVector< Attribute > &parameters)
Parse an parameter list if present.
static ParseResult parseParameterList (OpAsmParser &parser, ArrayAttr &parameters)
Shim to also use this for the InstanceOp custom parser.
static void printParameterList (OpAsmPrinter &p, Operation *op, ArrayAttr parameters)
Print a parameter list for a module or instance. Same format as HW dialect.
static ParseResult parseModuleLikeOp (OpAsmParser &parser, OperationState &result, bool withParameters=false)
template<typename ModuleTy >
static void printModuleLikeOp (mlir::FunctionOpInterface moduleLike, OpAsmPrinter &p, Attribute parameters=nullptr)
static LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1073 of file MSFTOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, const hw::ModulePortInfo & ports) static
Definition at line 44 of file MSFTOps.cpp.
References builder, circt::calyx::direction::get(), and circt::hw::INOUT.
checkParameterInContext()
static LogicalResult checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs) static
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated. Same format as HW dialect.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 694 of file MSFTOps.cpp.
hasAttribute()
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs) static
Definition at line 35 of file MSFTOps.cpp.
parseImplicitInnerRef()
static ParseResult parseImplicitInnerRef (OpAsmParser & p, hw::InnerRefAttr & innerRef) static
Definition at line 158 of file MSFTOps.cpp.
References circt::calyx::direction::get().
parseListOptionalRegLocList()
static ParseResult parseListOptionalRegLocList (OpAsmParser & p, LocationVectorAttr & locs) static
Definition at line 132 of file MSFTOps.cpp.
References circt::calyx::direction::get().
parseModuleLikeOp()
static ParseResult parseModuleLikeOp (OpAsmParser & parser, OperationState & result, bool withParameters = false) static
Definition at line 237 of file MSFTOps.cpp.
parseParameterList() [1/2]
static ParseResult parseParameterList (OpAsmParser & parser, ArrayAttr & parameters) static
Shim to also use this for the InstanceOp custom parser.
Definition at line 208 of file MSFTOps.cpp.
References circt::calyx::direction::get(), and parseParameterList().
parseParameterList() [2/2]
static ParseResult parseParameterList (OpAsmParser & parser, SmallVector< Attribute > & parameters) static
Parse an parameter list if present.
Same format as HW dialect. module-parameter-list ::= < parameter-decl (, parameter-decl)* > parameter-decl ::= identifier : type parameter-decl ::= identifier : type = attribute
Definition at line 182 of file MSFTOps.cpp.
References builder, and circt::calyx::direction::get().
Referenced by parseParameterList().
parsePhysLoc()
static ParseResult parsePhysLoc (OpAsmParser & p, PhysLocationAttr & attr) static
Definition at line 105 of file MSFTOps.cpp.
References circt::calyx::direction::get().
printImplicitInnerRef()
void printImplicitInnerRef (OpAsmPrinter & p, Operation * , hw::InnerRefAttr innerRef)
Definition at line 171 of file MSFTOps.cpp.
References circt::calyx::direction::get().
printListOptionalRegLocList()
static void printListOptionalRegLocList (OpAsmPrinter & p, Operation * , LocationVectorAttr locs) static
Definition at line 149 of file MSFTOps.cpp.
printModuleLikeOp()
template<typename ModuleTy > static void printModuleLikeOp (mlir::FunctionOpInterface moduleLike, OpAsmPrinter & p, Attribute parameters = nullptr) static
Definition at line 305 of file MSFTOps.cpp.
printParameterList()
static void printParameterList (OpAsmPrinter & p, Operation * op, ArrayAttr parameters) static
Print a parameter list for a module or instance. Same format as HW dialect.
Definition at line 220 of file MSFTOps.cpp.
printPhysLoc()
static void printPhysLoc (OpAsmPrinter & p, Operation * , PhysLocationAttr loc) static
Definition at line 127 of file MSFTOps.cpp.