CIRCT: circt::hw Namespace Reference
circt::hw Namespace Reference
Namespaces
detail
instance_like_impl
module_like_impl
Classes
struct InnerName
class InstanceGraph
HW-specific instance graph with a virtual entry node linking to all publicly visible modules.
struct PortInfo
This holds the name, type, direction of a module's ports.
struct ModulePortInfo
This holds a decoded list of input/inout and output ports for a module or instance.
class HWModulePortAccessor
struct HWReducePatternDialectInterface
A dialect interface to provide reduction patterns to a reducer tool.
class HWSymbolCache
This stores lookup tables to make manipulating and working with the IR more efficient.
class TypeVariant
Utility type that wraps a type that may be one of several possible Types.
class TypeAliasOr
class TypeOpVisitor
This helps visit TypeOp nodes.
class StmtVisitor
This helps visit TypeOp nodes.
class InnerSymTarget
The target of an inner symbol, the entity the symbol is a handle for.
class InnerSymbolTable
A table of inner symbols and their resolutions.
class InnerSymbolTableCollection
This class represents a collection of InnerSymbolTable's.
struct InnerRefNamespace
This class represents the namespace in which InnerRef's can be resolved.
class InstanceRecord
This is an edge in the InstanceGraph.
class InstanceGraphNode
This is a Node in the InstanceGraph.
class InstanceGraphBase
This graph tracks modules and where they are instantiated.
struct InstancePathCache
A data structure that caches and provides absolute paths to module instances in the IR.
struct ModuleNamespace
Typedefs
using HWModuleBuilder = llvm::function_ref< void(OpBuilder &, HWModulePortAccessor &)>
using InstancePath = ArrayRef< HWInstanceLike >
An absolute instance path.
Enumerations
enum class PortDirection { INPUT = 1 , OUTPUT = 2 , INOUT = 3 }
A module port direction.
Functions
mlir::FailureOr< mlir::Type > evaluateParametricType (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Type type)
Returns a resolved version of 'type' wherein any parameter reference has been evaluated based on the set of provided 'parameters'.
mlir::FailureOr< mlir::TypedAttr > evaluateParametricAttr (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Attribute paramAttr)
Evaluates a parametric attribute (param.decl.ref/param.expr) based on a set of provided parameter values.
bool isParametricType (mlir::Type t)
Returns true if any part of t is parametric.
LogicalResult verifyInnerSymAttr (InnerSymbolOpInterface op)
Verification hook for verifying InnerSym Attribute.
PortDirection flip (PortDirection direction)
Flip a port direction.
ModulePortInfo getModulePortInfo (Operation *op)
TODO: Move all these functions to a hw::ModuleLike interface.
SmallVector< PortInfo > getAllModulePortInfos (Operation *op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
PortInfo getModuleInOrInoutPort (Operation *op, size_t idx)
Return the PortInfo for the specified input or inout port.
PortInfo getModuleOutputPort (Operation *op, size_t idx)
Return the PortInfo for the specified output port.
void modifyModulePorts (Operation *op, ArrayRef< std::pair< unsigned, PortInfo >> insertInputs, ArrayRef< std::pair< unsigned, PortInfo >> insertOutputs, ArrayRef< unsigned > removeInputs, ArrayRef< unsigned > removeOutputs, Block *body=nullptr)
Insert and remove ports of a module.
bool isAnyModule (Operation *module)
Return true if this is an hw.module, external module, generated module etc.
bool isAnyModuleOrInstance (Operation *module)
Return true if isAnyModule or instance.
FunctionType getModuleType (Operation *module)
Return the signature for the specified module as a function type.
unsigned getModuleNumInputs (Operation *moduleOrInstance)
Return the number of inputs for the specified module/instance.
unsigned getModuleNumOutputs (Operation *moduleOrInstance)
Return the number of outputs for the specified module/instance.
StringAttr getVerilogModuleNameAttr (Operation *module)
Returns the verilog module name attribute or symbol name of any module-like operations.
StringRef getVerilogModuleName (Operation *module)
StringAttr getModuleArgumentNameAttr (Operation *module, size_t argNo)
Return the port name for the specified argument or result.
StringAttr getModuleResultNameAttr (Operation *module, size_t resultNo)
static StringRef getModuleArgumentName (Operation *module, size_t argNo)
static StringRef getModuleResultName (Operation *module, size_t resultNo)
LocationAttr getModuleArgumentLocAttr (Operation *module, size_t argNo)
Return the port location for the specified argument or result.
LocationAttr getModuleResultLocAttr (Operation *module, size_t resultNo)
bool isValidIndexBitWidth (Value index, Value array)
void setModuleArgumentNames (Operation *module, ArrayRef< Attribute > names)
void setModuleResultNames (Operation *module, ArrayRef< Attribute > names)
void setModuleArgumentLocs (Operation *module, ArrayRef< Attribute > locs)
void setModuleResultLocs (Operation *module, ArrayRef< Attribute > locs)
bool isCombinational (Operation *op)
Return true if the specified operation is a combinational logic op.
bool isValidParameterExpression (Attribute attr, Operation *module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs=false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
LogicalResult checkParameterInContext (Attribute value, ArrayAttr moduleParameters, const std::function< void(std::function< bool(InFlightDiagnostic &)>)> &instanceError, bool disallowParamRefs=false)
Check parameter specified by value to see if it is valid according to the module's parameters.
InnerSymAttr getArgSym (Operation *op, unsigned i)
Return the symbol (if exists, else null) on the corresponding input port argument.
InnerSymAttr getResultSym (Operation *op, unsigned i)
Return the symbol (if any, else null) on the corresponding output port argument.
bool isOffset (Value base, Value index, uint64_t offset)
std::unique_ptr< mlir::Pass > createPrintInstanceGraphPass ()
std::unique_ptr< mlir::Pass > createHWSpecializePass ()
std::unique_ptr< mlir::Pass > createPrintHWModuleGraphPass ()
std::unique_ptr< mlir::Pass > createFlattenIOPass ()
void registerReducePatternDialectInterface (mlir::DialectRegistry &registry)
Register the HW Reduction pattern dialect interface to the given registry.
mlir::Type getCanonicalType (mlir::Type type)
bool isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
bool isHWEnumType (mlir::Type type)
Return true if the specified type is a HW Enum type.
bool isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
int64_t getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
bool hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
template<typename... BaseTy>
bool type_isa (Type type)
template<typename... BaseTy>
bool type_isa_and_nonnull (Type type)
template<typename BaseTy >
BaseTy type_cast (Type type)
template<typename BaseTy >
BaseTy type_dyn_cast (Type type)
template<typename OS >
OS & operator<< (OS &os, const InnerSymTarget &target)
Printing InnerSymTarget's.
template<typename T >
static T & formatInstancePath (T &into, const InstancePath &path)
template<typename T >
static T & operator<< (T &os, const InstancePath &path)
Typedef Documentation
HWModuleBuilder
using circt::hw::HWModuleBuilder = typedef llvm::function_ref<void(OpBuilder &, HWModulePortAccessor &)>
Definition at line 197 of file HWOps.h.
InstancePath
using circt::hw::InstancePath = typedef ArrayRef<HWInstanceLike>
An absolute instance path.
Definition at line 266 of file InstanceGraphBase.h.
Enumeration Type Documentation
PortDirection
enum circt::hw::PortDirection strong
A module port direction.
Enumerator
INPUT
OUTPUT
INOUT
Definition at line 25 of file HWOpInterfaces.h.
Function Documentation
checkParameterInContext() [1/2]
LogicalResult circt::hw::checkParameterInContext (Attribute value, ArrayAttr moduleParameters, const std::function< void(std::function< bool(InFlightDiagnostic &)>)> & instanceError, bool disallowParamRefs = false)
Check parameter specified by value to see if it is valid according to the module's parameters.
If not, emit an error to the diagnostic provided as an argument to the lambda 'instanceError' and return failure, otherwise return success.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 115 of file HWOps.cpp.
References checkParameterInContext().
checkParameterInContext() [2/2]
LogicalResult circt::hw::checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs = false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success.
If disallowParamRefs is true, then parameter references are not allowed.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 189 of file HWOps.cpp.
Referenced by checkParameterInContext(), isValidParameterExpression(), verifyModuleCommon(), and circt::hw::instance_like_impl::verifyParameterStructure().
createFlattenIOPass()
std::unique_ptr< Pass > circt::hw::createFlattenIOPass ()
Definition at line 352 of file FlattenIO.cpp.
createHWSpecializePass()
std::unique_ptr< Pass > circt::hw::createHWSpecializePass ()
Definition at line 429 of file HWSpecialize.cpp.
createPrintHWModuleGraphPass()
std::unique_ptr< mlir::Pass > circt::hw::createPrintHWModuleGraphPass ()
Definition at line 40 of file PrintHWModuleGraph.cpp.
References lec::errs().
createPrintInstanceGraphPass()
std::unique_ptr< mlir::Pass > circt::hw::createPrintInstanceGraphPass ()
Definition at line 34 of file HWPrintInstanceGraph.cpp.
References lec::errs().
evaluateParametricAttr()
mlir::FailureOr<mlir::TypedAttr> circt::hw::evaluateParametricAttr (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Attribute paramAttr)
Evaluates a parametric attribute (param.decl.ref/param.expr) based on a set of provided parameter values.
evaluateParametricType()
mlir::FailureOr<mlir::Type> circt::hw::evaluateParametricType (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Type type)
Returns a resolved version of 'type' wherein any parameter reference has been evaluated based on the set of provided 'parameters'.
Referenced by circt::hw::instance_like_impl::resolveParametricTypes(), and verifyPrimitiveOpType().
flip()
PortDirection circt::hw::flip (PortDirection direction)
Flip a port direction.
Definition at line 36 of file HWOps.cpp.
References INOUT, INPUT, and OUTPUT.
formatInstancePath()
template<typename T > static T& circt::hw::formatInstancePath (T & into, const InstancePath & path) inline static
Definition at line 269 of file InstanceGraphBase.h.
Referenced by operator<<().
getAllModulePortInfos()
SmallVector< PortInfo > circt::hw::getAllModulePortInfos (Operation * op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 1026 of file HWOps.cpp.
References getArgSym(), getModuleType(), getResultSym(), INOUT, INPUT, isAnyModuleOrInstance(), and OUTPUT.
Referenced by circt::esi::buildESIWrapper(), circt::esi::findValidReadySignals(), legalizeModuleLocalNames(), and circt::esi::resolvePortNames().
getArgSym()
InnerSymAttr circt::hw::getArgSym (Operation * op, unsigned i)
Return the symbol (if exists, else null) on the corresponding input port argument.
Return the symbol (if any, else null) on the corresponding input port argument.
Definition at line 232 of file HWOps.cpp.
References getArgAttrsName(), and isAnyModuleOrInstance().
Referenced by getAllModulePortInfos(), getModuleInOrInoutPort(), and getModulePortInfo().
getBitWidth()
int64_t circt::hw::getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
Does not reflect any encoding, padding, or storage scheme, just the bit (and wire width) of a statically-size type. Reflects the number of wires needed to transmit a value of this type. Returns -1 if the type is not known or cannot be statically computed.
Definition at line 100 of file HWTypes.cpp.
Referenced by llvm::DOTGraphTraits< circt::hw::HWModuleOp >::getEdgeAttributes(), hwGetBitWidth(), circt::ExportVerilog::isZeroBitType(), and toJSON().
getCanonicalType()
mlir::Type circt::hw::getCanonicalType (mlir::Type type)
Definition at line 39 of file HWTypes.cpp.
Referenced by getInnerTypes(), getStructType(), isHWEnumType(), isHWIntegerType(), isStructType(), isValidIndexBitWidth(), and circt::ExportVerilog::isZeroBitType().
getModuleArgumentLocAttr()
LocationAttr circt::hw::getModuleArgumentLocAttr (Operation * module, size_t argNo)
Return the port location for the specified argument or result.
These can only return a null LocationAttr when the IR is invalid.
Definition at line 598 of file HWOps.cpp.
Referenced by circt::hw::module_like_impl::printModuleSignature().
getModuleArgumentName()
static StringRef circt::hw::getModuleArgumentName (Operation * module, size_t argNo) inline static
Definition at line 105 of file HWOps.h.
References getModuleArgumentNameAttr().
Referenced by getAsmBlockArgumentNamesImpl(), getOperandName(), and circt::hw::module_like_impl::printModuleSignature().
getModuleArgumentNameAttr()
StringAttr circt::hw::getModuleArgumentNameAttr (Operation * module, size_t argNo)
Return the port name for the specified argument or result.
These can only return a null StringAttr when the IR is invalid.
Definition at line 568 of file HWOps.cpp.
Referenced by getModuleArgumentName().
getModuleInOrInoutPort()
PortInfo circt::hw::getModuleInOrInoutPort (Operation * op, size_t idx)
Return the PortInfo for the specified input or inout port.
Definition at line 1071 of file HWOps.cpp.
References getArgSym(), getModuleType(), INOUT, and INPUT.
getModuleNumInputs()
unsigned circt::hw::getModuleNumInputs (Operation * moduleOrInstance) inline
Return the number of inputs for the specified module/instance.
Definition at line 80 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
Referenced by getPortVerilogName().
getModuleNumOutputs()
unsigned circt::hw::getModuleNumOutputs (Operation * moduleOrInstance) inline
Return the number of outputs for the specified module/instance.
Definition at line 87 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
getModuleOutputPort()
PortInfo circt::hw::getModuleOutputPort (Operation * op, size_t idx)
Return the PortInfo for the specified output port.
Definition at line 1093 of file HWOps.cpp.
References getModuleType(), getResultSym(), and OUTPUT.
getModulePortInfo()
ModulePortInfo circt::hw::getModulePortInfo (Operation * op)
TODO: Move all these functions to a hw::ModuleLike interface.
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 984 of file HWOps.cpp.
References getArgSym(), getModuleType(), getResultSym(), INOUT, INPUT, inputs, isAnyModuleOrInstance(), OUTPUT, and outputs.
Referenced by circt::msft::getModulePortInfo(), circt::msft::getValueName(), lowerInstanceResults(), spillWiresForInstanceInputs(), and circt::msft::PassCommon::verifyInstances().
getModuleResultLocAttr()
LocationAttr circt::hw::getModuleResultLocAttr (Operation * module, size_t resultNo)
Definition at line 606 of file HWOps.cpp.
Referenced by circt::hw::module_like_impl::printModuleSignature().
getModuleResultName()
static StringRef circt::hw::getModuleResultName (Operation * module, size_t resultNo) inline static
Definition at line 109 of file HWOps.h.
References getModuleResultNameAttr().
getModuleResultNameAttr()
StringAttr circt::hw::getModuleResultNameAttr (Operation * module, size_t resultNo)
Definition at line 576 of file HWOps.cpp.
Referenced by getModuleResultName(), and circt::hw::module_like_impl::printModuleSignature().
getModuleType()
FunctionType circt::hw::getModuleType (Operation * module)
Return the signature for the specified module as a function type.
Return the signature for a module as a function type from the module itself or from an hw::InstanceOp.
Definition at line 542 of file HWOps.cpp.
References circt::calyx::direction::get(), inputs, and isAnyModule().
Referenced by circt::esi::buildESIWrapper(), getAllModulePortInfos(), getModuleInOrInoutPort(), getModuleOutputPort(), getModulePortInfo(), setModuleArgumentLocs(), setModuleArgumentNames(), setModuleResultLocs(), setModuleResultNames(), circt::hw::instance_like_impl::verifyInstanceOfHWModule(), and verifyModuleCommon().
getResultSym()
InnerSymAttr circt::hw::getResultSym (Operation * op, unsigned i)
Return the symbol (if any, else null) on the corresponding output port argument.
Definition at line 247 of file HWOps.cpp.
References getResAttrsName(), and isAnyModuleOrInstance().
Referenced by getAllModulePortInfos(), getModuleOutputPort(), and getModulePortInfo().
getVerilogModuleName()
StringRef circt::hw::getVerilogModuleName (Operation * module) inline
Definition at line 96 of file HWOps.h.
References getVerilogModuleNameAttr().
Referenced by extractHierarchyFromTop(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), circt::ExportVerilog::getSymOpName(), and printHierarchy().
getVerilogModuleNameAttr()
StringAttr circt::hw::getVerilogModuleNameAttr (Operation * module)
Returns the verilog module name attribute or symbol name of any module-like operations.
Return the name to use for the Verilog module that we're referencing here.
This is typically the symbol, but can be overridden with the verilogName attribute.
Definition at line 559 of file HWOps.cpp.
Referenced by createModuleForCut(), circt::ExportVerilog::getSymOpName(), getVerilogModuleName(), and circt::ExportVerilog::GlobalNameResolver::GlobalNameResolver().
hasHWInOutType()
bool circt::hw::hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
Unlike isHWValueType, this is not conservative, it only returns false on known InOut types, rather than any unknown types.
isAnyModule()
bool circt::hw::isAnyModule (Operation * module)
Return true if this is an hw.module, external module, generated module etc.
Definition at line 530 of file HWOps.cpp.
Referenced by circt::hw::instance_like_impl::getHWModuleArgAndResultNames(), getModuleType(), getOperandName(), circt::msft::getValueName(), circt::msft::isAnyModule(), isAnyModuleOrInstance(), setModuleArgumentLocs(), setModuleArgumentNames(), setModuleResultLocs(), setModuleResultNames(), circt::msft::PassCommon::verifyInstances(), verifyModuleCommon(), and circt::hw::instance_like_impl::verifyReferencedModule().
isAnyModuleOrInstance()
bool circt::hw::isAnyModuleOrInstance (Operation * module)
Return true if isAnyModule or instance.
Definition at line 536 of file HWOps.cpp.
References isAnyModule().
Referenced by getAllModulePortInfos(), getArgSym(), getModuleNumInputs(), getModuleNumOutputs(), getModulePortInfo(), and getResultSym().
isCombinational()
bool circt::hw::isCombinational (Operation * op)
Return true if the specified operation is a combinational logic op.
Definition at line 59 of file HWOps.cpp.
References circt::hw::TypeOpVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchTypeOpVisitor().
isHWEnumType()
bool circt::hw::isHWEnumType (mlir::Type type)
Return true if the specified type is a HW Enum type.
Definition at line 63 of file HWTypes.cpp.
References getCanonicalType().
isHWIntegerType()
bool circt::hw::isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
This checks that it is a signless standard dialect type.
This checks that it is a signless standard dialect type or a hw::IntType.
Definition at line 50 of file HWTypes.cpp.
References getCanonicalType().
Referenced by simplifyCLog2(), simplifyDivS(), simplifyDivU(), simplifyModS(), simplifyModU(), simplifyShl(), simplifyShrS(), and simplifyShrU().
isHWValueType()
bool circt::hw::isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
Referenced by hwTypeIsAValueType().
isOffset()
bool circt::hw::isOffset (Value base, Value index, uint64_t offset)
Definition at line 1808 of file HWOps.cpp.
References bits().
Referenced by foldCreateToSlice(), mergeConcatSlices(), and mergeNeiboringAssignments().
isParametricType()
bool circt::hw::isParametricType (mlir::Type t)
Returns true if any part of t is parametric.
Definition at line 1036 of file HWAttributes.cpp.
isValidIndexBitWidth()
bool circt::hw::isValidIndexBitWidth (Value index, Value array)
Definition at line 48 of file HWOps.cpp.
References getCanonicalType().
isValidParameterExpression()
bool circt::hw::isValidParameterExpression (Attribute attr, Operation * module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
Definition at line 208 of file HWOps.cpp.
References checkParameterInContext().
modifyModulePorts()
void circt::hw::modifyModulePorts (Operation * op, ArrayRef< std::pair< unsigned, PortInfo >> insertInputs, ArrayRef< std::pair< unsigned, PortInfo >> insertOutputs, ArrayRef< unsigned > removeInputs, ArrayRef< unsigned > removeOutputs, Block * body = nullptr)
Insert and remove ports of a module.
The insertion and removal indices must be in ascending order. The indices refer to the port positions before any insertion or removal occurs. Ports inserted at the same index will appear in the module in the same order as they were listed in the insert* array. If 'body' is provided, additionally inserts/removes the corresponding block arguments.
The insertion and removal indices must be in ascending order. The indices refer to the port positions before any insertion or removal occurs. Ports inserted at the same index will appear in the module in the same order as they were listed in the insert* array.
The operation must be any of the module-like operations.
Definition at line 790 of file HWOps.cpp.
References circt::calyx::direction::get(), and modifyModuleArgs().
operator<<() [1/2]
template<typename OS > OS& circt::hw::operator<< (OS & os, const InnerSymTarget & target)
Printing InnerSymTarget's.
Definition at line 245 of file InnerSymbolTable.h.
References circt::hw::InnerSymTarget::getField(), circt::hw::InnerSymTarget::getOp(), circt::hw::InnerSymTarget::getPort(), circt::hw::InnerSymTarget::isField(), and circt::hw::InnerSymTarget::isPort().
operator<<() [2/2]
template<typename T > static T& circt::hw::operator<< (T & os, const InstancePath & path) static
Definition at line 278 of file InstanceGraphBase.h.
References formatInstancePath().
registerReducePatternDialectInterface()
void circt::hw::registerReducePatternDialectInterface (mlir::DialectRegistry & registry)
Register the HW Reduction pattern dialect interface to the given registry.
Definition at line 151 of file HWReductions.cpp.
setModuleArgumentLocs()
void circt::hw::setModuleArgumentLocs (Operation * module, ArrayRef< Attribute > locs)
Definition at line 614 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
setModuleArgumentNames()
void circt::hw::setModuleArgumentNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 584 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
setModuleResultLocs()
void circt::hw::setModuleResultLocs (Operation * module, ArrayRef< Attribute > locs)
Definition at line 621 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
setModuleResultNames()
void circt::hw::setModuleResultNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 591 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
type_cast()
template<typename BaseTy > BaseTy circt::hw::type_cast (Type type)
Definition at line 101 of file HWTypes.h.
type_dyn_cast()
template<typename BaseTy > BaseTy circt::hw::type_dyn_cast (Type type)
Definition at line 113 of file HWTypes.h.
type_isa()
template<typename... BaseTy> bool circt::hw::type_isa (Type type)
Definition at line 80 of file HWTypes.h.
Referenced by circt::hw::TypeVariant< Types >::classof(), and type_isa_and_nonnull().
type_isa_and_nonnull()
template<typename... BaseTy> bool circt::hw::type_isa_and_nonnull (Type type)
Definition at line 94 of file HWTypes.h.
References type_isa().
verifyInnerSymAttr()
LogicalResult circt::hw::verifyInnerSymAttr (InnerSymbolOpInterface op)
Verification hook for verifying InnerSym Attribute.
Definition at line 25 of file HWOpInterfaces.cpp.