CIRCT: circt::msft Namespace Reference
circt::msft Namespace Reference
Classes
class PrimitiveDB
A data structure to contain locations of the primitives on the device.
class PlacementDB
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
class TclEmitter
Instantiate for all Tcl emissions.
struct PassCommon
A set of methods which are broadly useful in a number of dialects.
struct MSFTPassCommon
struct RemoveOpLowering
Generic pattern for removing an op during pattern conversion.
Functions
LogicalResult parseOptionalRegLoc (SmallVectorImpl< PhysLocationAttr > &locs, AsmParser &p)
Parse and append a PhysLocAttr.
void printOptionalRegLoc (PhysLocationAttr loc, AsmPrinter &p)
Print out the above.
LogicalResult verifyDynInstData (Operation *)
std::unique_ptr< mlir::Pass > createWireCleanupPass ()
std::unique_ptr< mlir::Pass > createPartitionPass ()
std::unique_ptr< mlir::Pass > createLowerToHWPass ()
std::unique_ptr< mlir::Pass > createLowerInstancesPass ()
std::unique_ptr< mlir::Pass > createLowerConstructsPass ()
std::unique_ptr< mlir::Pass > createExportTclPass ()
std::unique_ptr< mlir::Pass > createDiscoverAppIDsPass ()
bool isAnyModule (Operation *module)
TODO: Migrate these to some sort of OpInterface shared with hw.
hw::ModulePortInfo getModulePortInfo (Operation *op)
SmallVector< unsigned > makeSequentialRange (unsigned size)
Utility for creating {0, 1, 2, ..., size}.
StringRef getValueName (Value v, const SymbolCache &syms, std::string &buff)
Try to get a "good" name for the given Value.
Function Documentation
createDiscoverAppIDsPass()
std::unique_ptr< Pass > circt::msft::createDiscoverAppIDsPass ()
Definition at line 113 of file MSFTDiscoverAppIDs.cpp.
createExportTclPass()
std::unique_ptr< Pass > circt::msft::createExportTclPass ()
Definition at line 101 of file MSFTExportTcl.cpp.
createLowerConstructsPass()
std::unique_ptr< Pass > circt::msft::createLowerConstructsPass ()
Definition at line 207 of file MSFTLowerConstructs.cpp.
createLowerInstancesPass()
std::unique_ptr< Pass > circt::msft::createLowerInstancesPass ()
Definition at line 190 of file MSFTLowerInstances.cpp.
createLowerToHWPass()
std::unique_ptr< Pass > circt::msft::createLowerToHWPass ()
Definition at line 259 of file MSFTToHW.cpp.
createPartitionPass()
std::unique_ptr< Pass > circt::msft::createPartitionPass ()
Definition at line 773 of file MSFTPartition.cpp.
createWireCleanupPass()
std::unique_ptr< Pass > circt::msft::createWireCleanupPass ()
Definition at line 159 of file MSFTWireCleanup.cpp.
getModulePortInfo()
hw::ModulePortInfo circt::msft::getModulePortInfo (Operation * op)
Definition at line 21 of file PassCommon.cpp.
References circt::hw::getModulePortInfo().
Referenced by getOperandName().
getValueName()
StringRef circt::msft::getValueName (Value v, const SymbolCache & syms, std::string & buff)
Try to get a "good" name for the given Value.
Definition at line 36 of file PassCommon.cpp.
References circt::SymbolCache::getDefinition(), circt::hw::getModulePortInfo(), and circt::hw::isAnyModule().
Referenced by circt::msft::MSFTPassCommon::dedupInputs(), and getResultName().
isAnyModule()
bool circt::msft::isAnyModule (Operation * module)
TODO: Migrate these to some sort of OpInterface shared with hw.
Definition at line 16 of file PassCommon.cpp.
References circt::hw::isAnyModule().
Referenced by getOperandName().
makeSequentialRange()
SmallVector< unsigned > circt::msft::makeSequentialRange (unsigned size)
Utility for creating {0, 1, 2, ..., size}.
Definition at line 29 of file PassCommon.cpp.
References size().
Referenced by circt::msft::MSFTPassCommon::dedupOutputs().
parseOptionalRegLoc()
LogicalResult circt::msft::parseOptionalRegLoc (SmallVectorImpl< PhysLocationAttr > & locs, AsmParser & p)
Parse and append a PhysLocAttr.
Options are '*' for null location, <x, y, num> for a location which is implicitily a FF, or a full phys location attribute.
Definition at line 88 of file MSFTAttributes.cpp.
printOptionalRegLoc()
void circt::msft::printOptionalRegLoc (PhysLocationAttr loc, AsmPrinter & p)
Print out the above.
Definition at line 112 of file MSFTAttributes.cpp.
verifyDynInstData()
LogicalResult circt::msft::verifyDynInstData (Operation * op)
Definition at line 15 of file MSFTOpInterfaces.cpp.