CIRCT: circt::firtool Namespace Reference
circt::firtool Namespace Reference
Classes
struct FirtoolOptions
Functions
LogicalResult populateCHIRRTLToLowFIRRTL (mlir::PassManager &pm, const FirtoolOptions &opt, ModuleOp module, StringRef inputFilename)
LogicalResult populateLowFIRRTLToHW (mlir::PassManager &pm, const FirtoolOptions &opt)
LogicalResult populateHWToSV (mlir::PassManager &pm, const FirtoolOptions &opt)
Function Documentation
populateCHIRRTLToLowFIRRTL()
LogicalResult circt::firtool::populateCHIRRTLToLowFIRRTL (mlir::PassManager & pm, const FirtoolOptions & opt, ModuleOp module, StringRef inputFilename)
Definition at line 23 of file Firtool.cpp.
References circt::firrtl::PreserveAggregate::All, circt::firtool::FirtoolOptions::blackBoxRootPath, circt::firtool::FirtoolOptions::chiselInterfaceOutDirectory, circt::firrtl::createAddSeqMemPortsPass(), circt::firrtl::createBlackBoxReaderPass(), circt::firrtl::createCheckCombCyclesPass(), circt::firrtl::createCheckCombLoopsPass(), circt::firrtl::createCreateSiFiveMetadataPass(), circt::arc::createDedupPass(), circt::firrtl::createDropConstPass(), circt::firrtl::createDropNamesPass(), circt::firrtl::createEmitOMIRPass(), circt::firrtl::createExpandWhensPass(), circt::createExportChiselInterfacePass(), circt::createExportSplitChiselInterfacePass(), circt::firrtl::createExtractInstancesPass(), circt::firrtl::createFlattenMemoryPass(), circt::firrtl::createGrandCentralPass(), circt::firrtl::createIMConstPropPass(), circt::firrtl::createIMDeadCodeElimPass(), circt::firrtl::createInferReadWritePass(), circt::firrtl::createInferResetsPass(), circt::firrtl::createInferWidthsPass(), circt::firrtl::createInjectDUTHierarchyPass(), circt::firrtl::createInlinerPass(), circt::firrtl::createInnerSymbolDCEPass(), circt::firrtl::createLowerCHIRRTLPass(), circt::firrtl::createLowerFIRRTLTypesPass(), circt::firrtl::createLowerIntrinsicsPass(), circt::firrtl::createLowerMatchesPass(), circt::firrtl::createLowerMemoryPass(), circt::firrtl::createMemToRegOfVecPass(), circt::firrtl::createMergeConnectionsPass(), circt::firrtl::createPrefixModulesPass(), circt::firrtl::createRandomizeRegisterInitPass(), circt::firrtl::createRegisterOptimizerPass(), circt::firrtl::createSFCCompatPass(), createSimpleCanonicalizerPass(), circt::firrtl::createVBToBVPass(), circt::firrtl::createVectorizationPass(), circt::firrtl::createWireDFTPass(), circt::firtool::FirtoolOptions::dedup, circt::firtool::FirtoolOptions::disableAggressiveMergeConnections, circt::firtool::FirtoolOptions::disableOptimization, circt::firtool::FirtoolOptions::emitOMIR, circt::firtool::FirtoolOptions::exportChiselInterface, circt::firtool::FirtoolOptions::getPreserveMode(), circt::firtool::FirtoolOptions::grandCentralInstantiateCompanionOnly, circt::firtool::FirtoolOptions::ignoreReadEnableMem, circt::firtool::FirtoolOptions::isRandomEnabled(), circt::firtool::FirtoolOptions::lowerMemories, circt::firtool::FirtoolOptions::omirOutFile, circt::firtool::FirtoolOptions::preserveAggregate, circt::firtool::FirtoolOptions::replSeqMem, circt::firtool::FirtoolOptions::replSeqMemCircuit, circt::firtool::FirtoolOptions::replSeqMemFile, circt::firtool::FirtoolOptions::useOldCheckCombCycles, and circt::firtool::FirtoolOptions::vbToBV.
populateHWToSV()
LogicalResult circt::firtool::populateHWToSV (mlir::PassManager & pm, const FirtoolOptions & opt)
Definition at line 213 of file Firtool.cpp.
References circt::firtool::FirtoolOptions::addMuxPragmas, circt::firtool::FirtoolOptions::addVivadoRAMAddressConflictSynthesisBugWorkaround, circt::sv::createHWCleanupPass(), circt::sv::createHWMemSimImplPass(), circt::seq::createSeqFIRRTLLowerToSVPass(), createSimpleCanonicalizerPass(), circt::sv::createSVExtractTestCodePass(), circt::firtool::FirtoolOptions::disableOptimization, circt::firtool::FirtoolOptions::emitSeparateAlwaysBlocks, circt::firtool::FirtoolOptions::etcDisableInstanceExtraction, circt::firtool::FirtoolOptions::etcDisableModuleInlining, circt::firtool::FirtoolOptions::extractTestCode, circt::firtool::FirtoolOptions::ignoreReadEnableMem, circt::firtool::FirtoolOptions::isRandomEnabled(), and circt::firtool::FirtoolOptions::replSeqMem.
populateLowFIRRTLToHW()
LogicalResult circt::firtool::populateLowFIRRTLToHW (mlir::PassManager & pm, const FirtoolOptions & opt)
Definition at line 183 of file Firtool.cpp.
References circt::firtool::FirtoolOptions::addMuxPragmas, circt::createLowerFIRRTLToHWPass(), circt::firrtl::createLowerXMRPass(), circt::firrtl::createResolveTracesPass(), createSimpleCanonicalizerPass(), circt::firtool::FirtoolOptions::disableOptimization, circt::firtool::FirtoolOptions::emitChiselAssertsAsSVA, circt::firtool::FirtoolOptions::enableAnnotationWarning, circt::firtool::FirtoolOptions::isRandomEnabled(), and circt::firtool::FirtoolOptions::outputAnnotationFilename.