CIRCT: circt::esi Namespace Reference
circt::esi Namespace Reference
Namespaces
capnp
cosim
cppapi
detail
Classes
class ESIAPIType
struct ESIPortValidReadyMapping
A triple of signals which represent a latency insensitive interface with valid/ready semantics.
struct ServicePortInfo
Describes a service port.
class ServiceGeneratorDispatcher
Class which "dispatches" a service implementation request to its specified generator.
Functions
void registerESIPasses ()
void registerESITranslations ()
LogicalResult exportCosimSchema (ModuleOp module, llvm::raw_ostream &os)
void findValidReadySignals (Operation *modOp, SmallVectorImpl< ESIPortValidReadyMapping > &names)
Find all the port triples on a module which fit the <name>/<name>_valid/<name>_ready pattern.
void resolvePortNames (Operation *modOp, ArrayRef< StringRef > portNames, SmallVectorImpl< ESIPortValidReadyMapping > &names)
Given a list of logical port names, find the data/valid/ready port triples.
Operation * buildESIWrapper (OpBuilder &b, Operation *pearl, ArrayRef< ESIPortValidReadyMapping > portsToConvert)
Build an ESI module wrapper, converting the wires with latency-insensitive semantics to ESI channels and passing through the rest.
LogicalResult validateServiceConnectionRequest (ServiceDeclOpInterface decl, Operation *reqOp)
Validate a connection request against a service decl by comparing against the port list.
std::unique_ptr< OperationPass< ModuleOp > > createESIEmitCollateralPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESIPhysicalLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESIPortLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESITypeLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESItoHWPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESIConnectServicesPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESIAddCPPAPIPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESICleanMetadataPass ()
mlir::Type innerType (mlir::Type type)
static bool isSupported (Type type, bool outer=false)
Returns true if the type is currently supported.
static void emitName (Type type, uint64_t id, llvm::raw_ostream &os)
Write a valid Capnp name for 'type'.
Variables
constexpr uint64_t esiApiVersion = 1
Every time we implement a breaking change in the schema generation, increment this number.
constexpr StringRef extModBundleSignalsAttrName = "esi.bundle"
Name of dialect attribute which governs whether or not to bundle (i.e.
constexpr StringRef extModPortFlattenStructsAttrName = "esi.portFlattenStructs"
Name of dialect attribute which governs whether or not to flatten struct ports into a bunch of individual 'data' wires.
constexpr StringRef extModPortInSuffix = "esi.portInSuffix"
Suffix all lowered input ports with this suffix. Defaults to nothing.
constexpr StringRef extModPortOutSuffix = "esi.portOutSuffix"
Suffix all lowered output ports with this suffix. Defaults to nothing.
constexpr StringRef extModPortValidSuffix = "esi.portValidSuffix"
Suffix lowered valid ports with this suffix.
constexpr StringRef extModPortReadySuffix = "esi.portReadySuffix"
Suffix lowered ready ports with this suffix.
constexpr StringRef extModPortRdenSuffix = "esi.portRdenSuffix"
Suffix lowered read enable ports with this suffix.
constexpr StringRef extModPortEmptySuffix = "esi.portEmptySuffix"
Suffix lowered empty ports with this suffix.
Function Documentation
buildESIWrapper()
Operation * circt::esi::buildESIWrapper (OpBuilder & b, Operation * pearl, ArrayRef< ESIPortValidReadyMapping > portsToConvert)
Build an ESI module wrapper, converting the wires with latency-insensitive semantics to ESI channels and passing through the rest.
Definition at line 150 of file ESIDialect.cpp.
References circt::hw::PortInfo::argNum, circt::calyx::direction::get(), circt::BackedgeBuilder::get(), circt::hw::getAllModulePortInfos(), circt::hw::getModuleType(), circt::hw::INOUT, circt::hw::INPUT, circt::hw::OUTPUT, outputs, and circt::hw::PortInfo::type.
Referenced by circtESIWrapModule().
createESIAddCPPAPIPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIAddCPPAPIPass ()
Definition at line 79 of file ESIAddCPPAPI.cpp.
createESICleanMetadataPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESICleanMetadataPass ()
Definition at line 46 of file ESICleanMetadata.cpp.
createESIConnectServicesPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIConnectServicesPass ()
Definition at line 687 of file ESIServices.cpp.
createESIEmitCollateralPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIEmitCollateralPass ()
Definition at line 278 of file ESIEmitCollateral.cpp.
createESIPhysicalLoweringPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIPhysicalLoweringPass ()
Definition at line 196 of file ESILowerPhysical.cpp.
createESIPortLoweringPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIPortLoweringPass ()
Definition at line 957 of file ESILowerPorts.cpp.
createESItoHWPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESItoHWPass ()
Definition at line 519 of file ESILowerToHW.cpp.
createESITypeLoweringPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESITypeLoweringPass ()
Definition at line 104 of file ESILowerTypes.cpp.
emitName()
static void circt::esi::emitName (Type type, uint64_t id, llvm::raw_ostream & os) static
Write a valid Capnp name for 'type'.
Definition at line 79 of file APIUtilities.cpp.
Referenced by circt::esi::ESIAPIType::name().
exportCosimSchema()
LogicalResult circt::esi::exportCosimSchema (ModuleOp module, llvm::raw_ostream & os)
Definition at line 168 of file ESITranslations.cpp.
References circt::calyx::direction::get().
Referenced by circtESIExportCosimSchema(), and registerESITranslations().
findValidReadySignals()
void circt::esi::findValidReadySignals (Operation * modOp, SmallVectorImpl< ESIPortValidReadyMapping > & names)
Find all the port triples on a module which fit the <name>/<name>_valid/<name>_ready pattern.
Find all the port triples on a module which fit the <name>[_data]/<name>_valid/<name>_ready pattern.
Ready must be the opposite direction of the other two.
Definition at line 104 of file ESIDialect.cpp.
References findValidReady(), and circt::hw::getAllModulePortInfos().
innerType()
mlir::Type circt::esi::innerType (mlir::Type type)
Definition at line 151 of file ESITypes.cpp.
Referenced by getInnerTypes(), circt::moore::UnpackedType::getSimpleBitVectorOrNull(), getVerilogDeclWord(), hwTypeAliasTypeGet(), circt::TypeConversionPattern::matchAndRewrite(), circt::handshake::toValidType(), circt::handshake::tupleToStruct(), and circt::esi::cppapi::CPPEndpoint::writeType().
isSupported()
static bool circt::esi::isSupported (Type type, bool outer = false) static
Returns true if the type is currently supported.
Definition at line 35 of file APIUtilities.cpp.
Referenced by circt::esi::ESIAPIType::isSupported().
registerESIPasses()
void circt::esi::registerESIPasses ()
Definition at line 220 of file ESIPasses.cpp.
References registerPasses().
Referenced by circt::registerAllPasses(), and registerESIPasses().
registerESITranslations()
void circt::esi::registerESITranslations ()
Definition at line 180 of file ESITranslations.cpp.
References exportCosimSchema().
Referenced by circt::registerAllTranslations().
resolvePortNames()
void circt::esi::resolvePortNames (Operation * modOp, ArrayRef< StringRef > portNames, SmallVectorImpl< ESIPortValidReadyMapping > & names)
Given a list of logical port names, find the data/valid/ready port triples.
Definition at line 117 of file ESIDialect.cpp.
References findValidReady(), and circt::hw::getAllModulePortInfos().
Referenced by circtESIWrapModule().
validateServiceConnectionRequest()
LogicalResult circt::esi::validateServiceConnectionRequest (ServiceDeclOpInterface decl, Operation * reqOp)
Validate a connection request against a service decl by comparing against the port list.
Definition at line 430 of file ESIOps.cpp.
References validateRequest().
Variable Documentation
esiApiVersion
constexpr uint64_t circt::esi::esiApiVersion = 1 constexpr
Every time we implement a breaking change in the schema generation, increment this number.
It is a seed for all the schema hashes.
Definition at line 28 of file APIUtilities.h.
Referenced by circt::esi::ESIAPIType::typeID().
extModBundleSignalsAttrName
constexpr StringRef circt::esi::extModBundleSignalsAttrName = "esi.bundle" constexpr
Name of dialect attribute which governs whether or not to bundle (i.e.
use SystemVerilog interfaces) channel signal wires on external modules.
Definition at line 42 of file ESIDialect.h.
extModPortEmptySuffix
constexpr StringRef circt::esi::extModPortEmptySuffix = "esi.portEmptySuffix" constexpr
Suffix lowered empty ports with this suffix.
Defaults to "_empty". Applies only to FIFO channels.
Definition at line 63 of file ESIDialect.h.
extModPortFlattenStructsAttrName
constexpr StringRef circt::esi::extModPortFlattenStructsAttrName = "esi.portFlattenStructs" constexpr
Name of dialect attribute which governs whether or not to flatten struct ports into a bunch of individual 'data' wires.
Definition at line 46 of file ESIDialect.h.
extModPortInSuffix
constexpr StringRef circt::esi::extModPortInSuffix = "esi.portInSuffix" constexpr
Suffix all lowered input ports with this suffix. Defaults to nothing.
Definition at line 49 of file ESIDialect.h.
extModPortOutSuffix
constexpr StringRef circt::esi::extModPortOutSuffix = "esi.portOutSuffix" constexpr
Suffix all lowered output ports with this suffix. Defaults to nothing.
Definition at line 51 of file ESIDialect.h.
extModPortRdenSuffix
constexpr StringRef circt::esi::extModPortRdenSuffix = "esi.portRdenSuffix" constexpr
Suffix lowered read enable ports with this suffix.
Defaults to "_rden". Applies only to FIFO channels.
Definition at line 60 of file ESIDialect.h.
extModPortReadySuffix
constexpr StringRef circt::esi::extModPortReadySuffix = "esi.portReadySuffix" constexpr
Suffix lowered ready ports with this suffix.
Defaults to "_ready". Applies only to ValidReady channels.
Definition at line 57 of file ESIDialect.h.
extModPortValidSuffix
constexpr StringRef circt::esi::extModPortValidSuffix = "esi.portValidSuffix" constexpr
Suffix lowered valid ports with this suffix.
Defaults to "_valid". Applies only to ValidReady channels.
Definition at line 54 of file ESIDialect.h.