CIRCT: circt::firrtl::detail Namespace Reference
circt::firrtl::detail Namespace Reference
Classes
struct AnnoTargetImpl
struct FIRRTLBaseTypeStorage
struct WidthTypeStorage
struct BundleTypeStorage
struct OpenBundleTypeStorage
struct FVectorTypeStorage
struct OpenVectorTypeStorage
struct FEnumTypeStorage
Functions
RefType getForceableResultType (bool forceable, Type type)
Return null or forceable reference result type.
LogicalResult verifyForceableOp (Forceable op)
Verify a Forceable op.
Forceable replaceWithNewForceability (Forceable op, bool forceable, ::mlir::PatternRewriter *rewriter=nullptr)
Replace a Forceable op with equivalent, changing whether forceable.
Function Documentation
getForceableResultType()
RefType circt::firrtl::detail::getForceableResultType (bool forceable, Type type)
Return null or forceable reference result type.
Definition at line 109 of file FIRRTLOpInterfaces.cpp.
References circt::calyx::direction::get().
Referenced by verifyForceableOp().
replaceWithNewForceability()
Forceable circt::firrtl::detail::replaceWithNewForceability (Forceable op, bool forceable, ::mlir::PatternRewriter * rewriter = nullptr)
Replace a Forceable op with equivalent, changing whether forceable.
No-op if already has specified forceability.
Referenced by demoteForceableIfUnused().
verifyForceableOp()
LogicalResult circt::firrtl::detail::verifyForceableOp (Forceable op)
Verify a Forceable op.
Definition at line 118 of file FIRRTLOpInterfaces.cpp.
References circt::firrtl::data, and getForceableResultType().