CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Seq/SeqOps.cpp File Reference
SeqOps.cpp File Reference
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "llvm/ADT/SmallString.h"
#include "circt/Dialect/Seq/Seq.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static std::optional< APInt > getConstantInt (Attribute operand)
Determine the integer value of a constant operand.
static bool isConstantZero (Attribute operand)
Determine whether a constant operand is a zero value.
static bool isConstantOne (Attribute operand)
Determine whether a constant operand is a one value.
static void setNameFromResult (OpAsmParser &parser, OperationState &result)
static bool canElideName (OpAsmPrinter &p, Operation *op)
template<bool ClockEnabled>
static ParseResult parseCompReg (OpAsmParser &parser, OperationState &result)
static void printClockEnable (::mlir::OpAsmPrinter &p, CompRegOp op)
static void printClockEnable (::mlir::OpAsmPrinter &p, CompRegClockEnabledOp op)
template<class Op >
static void printCompReg (::mlir::OpAsmPrinter &p, Op op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 666 of file SeqOps.cpp.
Function Documentation
canElideName()
static bool canElideName (OpAsmPrinter & p, Operation * op) static
Definition at line 79 of file SeqOps.cpp.
Referenced by printCompReg().
getConstantInt()
static std::optional<APInt> getConstantInt (Attribute operand) static
Determine the integer value of a constant operand.
Definition at line 28 of file SeqOps.cpp.
Referenced by isConstantOne(), and isConstantZero().
isConstantOne()
static bool isConstantOne (Attribute operand) static
Determine whether a constant operand is a one value.
Definition at line 44 of file SeqOps.cpp.
References getConstantInt().
isConstantZero()
static bool isConstantZero (Attribute operand) static
Determine whether a constant operand is a zero value.
Definition at line 37 of file SeqOps.cpp.
References getConstantInt().
parseCompReg()
template<bool ClockEnabled> static ParseResult parseCompReg (OpAsmParser & parser, OperationState & result) static
Definition at line 226 of file SeqOps.cpp.
References circt::calyx::direction::get(), and setNameFromResult().
printClockEnable() [1/2]
static void printClockEnable (::mlir::OpAsmPrinter & p, CompRegClockEnabledOp op) static
Definition at line 279 of file SeqOps.cpp.
printClockEnable() [2/2]
static void printClockEnable (::mlir::OpAsmPrinter & p, CompRegOp op) static
Definition at line 277 of file SeqOps.cpp.
Referenced by printCompReg().
printCompReg()
template<class Op > static void printCompReg (::mlir::OpAsmPrinter & p, Op op) static
Definition at line 285 of file SeqOps.cpp.
References canElideName(), and printClockEnable().
setNameFromResult()
static void setNameFromResult (OpAsmParser & parser, OperationState & result) static
Definition at line 68 of file SeqOps.cpp.
References isdigit.
Referenced by parseCompReg().