CIRCT: circt::hw::InstancePathCache Struct Reference
circt::hw::InstancePathCache Struct Reference
A data structure that caches and provides absolute paths to module instances in the IR.
#include <InstanceGraphBase.h>
Public Member Functions
InstancePathCache (InstanceGraphBase &instanceGraph)
ArrayRef< InstancePath > getAbsolutePaths (HWModuleLike op)
void replaceInstance (HWInstanceLike oldOp, HWInstanceLike newOp)
Replace an InstanceOp. This is required to keep the cache updated.
Public Attributes
InstanceGraphBase & instanceGraph
The instance graph of the IR.
Private Member Functions
InstancePath appendInstance (InstancePath path, HWInstanceLike inst)
Append an instance to a path.
Private Attributes
llvm::BumpPtrAllocator allocator
An allocator for individual instance paths and entire path lists.
DenseMap< Operation *, ArrayRef< InstancePath > > absolutePathsCache
Cached absolute instance paths.
Detailed Description
A data structure that caches and provides absolute paths to module instances in the IR.
Definition at line 284 of file InstanceGraphBase.h.
Constructor & Destructor Documentation
InstancePathCache()
circt::hw::InstancePathCache::InstancePathCache (InstanceGraphBase & instanceGraph) inline explicit
Definition at line 288 of file InstanceGraphBase.h.
Member Function Documentation
appendInstance()
InstancePath InstancePathCache::appendInstance (InstancePath path, HWInstanceLike inst) private
Append an instance to a path.
Definition at line 244 of file InstanceGraphBase.cpp.
References allocator.
Referenced by getAbsolutePaths().
getAbsolutePaths()
ArrayRef< InstancePath > InstancePathCache::getAbsolutePaths (HWModuleLike op)
Definition at line 205 of file InstanceGraphBase.cpp.
References absolutePathsCache, allocator, appendInstance(), circt::hw::InstanceGraphBase::getTopLevelNode(), instanceGraph, and circt::hw::InstanceGraphNode::uses().
Referenced by circt::firrtl::applyGCTMemTaps(), circt::firrtl::applyWiring(), and lowerInternalPathAnno().
replaceInstance()
void InstancePathCache::replaceInstance (HWInstanceLike oldOp, HWInstanceLike newOp)
Replace an InstanceOp. This is required to keep the cache updated.
Definition at line 253 of file InstanceGraphBase.cpp.
References absolutePathsCache, allocator, instanceGraph, and circt::hw::InstanceGraphBase::replaceInstance().
Referenced by circt::firrtl::addPortsToModule().
Member Data Documentation
absolutePathsCache
DenseMap<Operation *, ArrayRef<InstancePath> > circt::hw::InstancePathCache::absolutePathsCache private
Cached absolute instance paths.
Definition at line 300 of file InstanceGraphBase.h.
Referenced by getAbsolutePaths(), and replaceInstance().
allocator
llvm::BumpPtrAllocator circt::hw::InstancePathCache::allocator private
An allocator for individual instance paths and entire path lists.
Definition at line 297 of file InstanceGraphBase.h.
Referenced by appendInstance(), getAbsolutePaths(), and replaceInstance().
instanceGraph
InstanceGraphBase& circt::hw::InstancePathCache::instanceGraph
The instance graph of the IR.
Definition at line 286 of file InstanceGraphBase.h.
Referenced by circt::firrtl::addPortsToModule(), getAbsolutePaths(), lookupInstNode(), lowerInternalPathAnno(), and replaceInstance().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/InstanceGraphBase.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/InstanceGraphBase.cpp