CIRCT: ResolveTracesPass Struct Reference
ResolveTracesPass Struct Reference
Public Member Functions
void runOnOperation () override
Private Member Functions
bool updateTargetImpl (Annotation &anno, FModuleLike &module, FIRRTLBaseType type, StringRef name)
Internal implementation that updates an Annotation to add a "target" field based on the current location of the annotation in the circuit.
bool updatePortTarget (FModuleLike &module, Annotation &anno, unsigned portIdx)
Add a "target" field to a port Annotation that indicates the current location of the port in the circuit.
bool updateTarget (FModuleLike &module, Operation *op, Annotation &anno)
Add a "target" field to an Annotation that indicates the current location of a component in the circuit.
bool updateModuleTarget (FModuleLike &module, Annotation &anno)
Add a "target" field to an Annotation on a Module that indicates the current location of the module.
Private Attributes
NLATable * nlaTable
Stores a pointer to an NLA Table.
Detailed Description
Definition at line 68 of file ResolveTraces.cpp.
Member Function Documentation
runOnOperation()
void ResolveTracesPass::runOnOperation () override
Definition at line 205 of file ResolveTraces.cpp.
References lec::dbgs(), circt::firrtl::getOrAddInnerSym(), circt::firrtl::AnnotationSet::removeAnnotations(), circt::firrtl::AnnotationSet::removePortAnnotations(), and circt::firrtl::transformReduce().
updateModuleTarget()
bool ResolveTracesPass::updateModuleTarget (FModuleLike & module, Annotation & anno) inline private
Add a "target" field to an Annotation on a Module that indicates the current location of the module.
This will be local or non-local depending on the Annotation.
Definition at line 174 of file ResolveTraces.cpp.
References lec::dbgs(), circt::calyx::direction::get(), circt::firrtl::Annotation::getDict(), circt::firrtl::Annotation::getMember(), circt::firrtl::NLATable::getNLA(), circt::firrtl::Annotation::isClass(), circt::firrtl::Annotation::setMember(), and circt::firrtl::traceAnnoClass.
updatePortTarget()
bool ResolveTracesPass::updatePortTarget (FModuleLike & module, Annotation & anno, unsigned portIdx) inline private
Add a "target" field to a port Annotation that indicates the current location of the port in the circuit.
Definition at line 139 of file ResolveTraces.cpp.
References circt::firrtl::getBaseType().
updateTarget()
bool ResolveTracesPass::updateTarget (FModuleLike & module, Operation * op, Annotation & anno) inline private
Add a "target" field to an Annotation that indicates the current location of a component in the circuit.
Definition at line 147 of file ResolveTraces.cpp.
References circt::firrtl::getBaseType().
updateTargetImpl()
bool ResolveTracesPass::updateTargetImpl (Annotation & anno, FModuleLike & module, FIRRTLBaseType type, StringRef name) inline private
Internal implementation that updates an Annotation to add a "target" field based on the current location of the annotation in the circuit.
The value of the "target" will be a local target if the Annotation is local and a non-local target if the Annotation is non-local.
Definition at line 82 of file ResolveTraces.cpp.
References lec::dbgs(), circt::calyx::direction::get(), circt::firrtl::Annotation::getDict(), circt::firrtl::Annotation::getFieldID(), circt::firrtl::Annotation::getMember(), circt::firrtl::NLATable::getNLA(), circt::firrtl::Annotation::isClass(), circt::firrtl::Annotation::setMember(), and circt::firrtl::traceAnnoClass.
Member Data Documentation
nlaTable
NLATable* ResolveTracesPass::nlaTable private
Stores a pointer to an NLA Table.
This is populated during runOnOperation.
Definition at line 76 of file ResolveTraces.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp