CIRCT: circt::esi::cppapi::CPPEndpoint Struct Reference
circt::esi::cppapi::CPPEndpoint Struct Reference
#include <CPPAPI.h>
Public Member Functions
CPPEndpoint (esi::ServicePortInfo portInfo, const llvm::MapVector< mlir::Type, CPPType > &types)
StringRef getName () const
std::string getTypeName () const
std::string getPointerTypeName () const
LogicalResult writeType (Location loc, mlir::raw_indented_ostream &os) const
LogicalResult writeDecl (Location loc, mlir::raw_indented_ostream &os) const
Public Attributes
esi::ServicePortInfo portInfo
const llvm::MapVector< mlir::Type, CPPType > & types
Detailed Description
Definition at line 53 of file CPPAPI.h.
Constructor & Destructor Documentation
CPPEndpoint()
circt::esi::cppapi::CPPEndpoint::CPPEndpoint (esi::ServicePortInfo portInfo, const llvm::MapVector< mlir::Type, CPPType > & types) inline
Definition at line 54 of file CPPAPI.h.
Member Function Documentation
getName()
StringRef circt::esi::cppapi::CPPEndpoint::getName () const inline
Definition at line 57 of file CPPAPI.h.
References circt::esi::ServicePortInfo::name, and portInfo.
Referenced by getTypeName().
getPointerTypeName()
std::string circt::esi::cppapi::CPPEndpoint::getPointerTypeName () const inline
Definition at line 59 of file CPPAPI.h.
References getTypeName().
Referenced by writeDecl().
getTypeName()
std::string circt::esi::cppapi::CPPEndpoint::getTypeName () const inline
Definition at line 58 of file CPPAPI.h.
References getName().
Referenced by getPointerTypeName(), and writeDecl().
writeDecl()
LogicalResult CPPEndpoint::writeDecl (Location loc, mlir::raw_indented_ostream & os) const
Definition at line 288 of file CPPAPI.cpp.
References getPointerTypeName(), getTypeName(), and writeType().
writeType()
LogicalResult CPPEndpoint::writeType (Location loc, mlir::raw_indented_ostream & os) const
Definition at line 250 of file CPPAPI.cpp.
References circt::esi::innerType(), portInfo, circt::esi::ServicePortInfo::toClientType, circt::esi::ServicePortInfo::toServerType, and types.
Referenced by writeDecl().
Member Data Documentation
portInfo
esi::ServicePortInfo circt::esi::cppapi::CPPEndpoint::portInfo
Definition at line 63 of file CPPAPI.h.
Referenced by getName(), and writeType().
types
const llvm::MapVector<mlir::Type, CPPType>& circt::esi::cppapi::CPPEndpoint::types
Definition at line 68 of file CPPAPI.h.
Referenced by writeType().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/Passes/CPPAPI/CPPAPI.cpp