CIRCT: circt::msft::MSFTPassCommon Struct Reference
circt::msft::MSFTPassCommon Struct Reference
#include <MSFTPassCommon.h>
Protected Member Functions
SmallVector< InstanceOp, 1 > updateInstances (MSFTModuleOp mod, ArrayRef< unsigned > newToOldResultMap, llvm::function_ref< void(InstanceOp, InstanceOp, SmallVectorImpl< Value > &)> getOperandsFunc)
Update all the instantiations of 'mod' to match the port list.
void getAndSortModules (ModuleOp topMod, SmallVectorImpl< MSFTModuleOp > &mods)
void bubbleWiresUp (MSFTModuleOp mod)
Push up any wires which are simply passed-through.
void dedupOutputs (MSFTModuleOp mod)
Remove outputs driven by the same value.
void sinkWiresDown (MSFTModuleOp mod)
Sink all the instance connections which are loops.
void dedupInputs (MSFTModuleOp mod)
Protected Member Functions inherited from circt::msft::PassCommon
LogicalResult verifyInstances (ModuleOp topMod)
void getAndSortModules (ModuleOp topMod, SmallVectorImpl< hw::HWModuleLike > &mods)
void getAndSortModulesVisitor (hw::HWModuleLike mod, SmallVectorImpl< hw::HWModuleLike > &mods, DenseSet< Operation * > &modsSeen)
Additional Inherited Members
Protected Attributes inherited from circt::msft::PassCommon
SymbolCache topLevelSyms
DenseMap< Operation *, SmallVector< hw::HWInstanceLike, 1 > > moduleInstantiations
Detailed Description
Definition at line 13 of file MSFTPassCommon.h.
Member Function Documentation
bubbleWiresUp()
void MSFTPassCommon::bubbleWiresUp (MSFTModuleOp mod) protected
Push up any wires which are simply passed-through.
Definition at line 94 of file MSFTWireCleanup.cpp.
References circt::hw::PortInfo::argNum, circt::hw::ModulePortInfo::inputs, and circt::hw::ModulePortInfo::outputs.
dedupInputs()
void MSFTPassCommon::dedupInputs (MSFTModuleOp mod) protected
Definition at line 16 of file MSFTPassCommon.cpp.
References circt::calyx::direction::get(), and circt::msft::getValueName().
dedupOutputs()
void MSFTPassCommon::dedupOutputs (MSFTModuleOp mod) protected
Remove outputs driven by the same value.
Definition at line 62 of file MSFTWireCleanup.cpp.
References circt::msft::makeSequentialRange().
getAndSortModules()
void MSFTPassCommon::getAndSortModules (ModuleOp topMod, SmallVectorImpl< MSFTModuleOp > & mods) protected
Definition at line 123 of file MSFTPassCommon.cpp.
sinkWiresDown()
void MSFTPassCommon::sinkWiresDown (MSFTModuleOp mod) protected
Sink all the instance connections which are loops.
Definition at line 68 of file MSFTPassCommon.cpp.
updateInstances()
SmallVector< InstanceOp, 1 > MSFTPassCommon::updateInstances (MSFTModuleOp mod, ArrayRef< unsigned > newToOldResultMap, llvm::function_ref< void(InstanceOp, InstanceOp, SmallVectorImpl< Value > &)> getOperandsFunc) protected
Update all the instantiations of 'mod' to match the port list.
For any output ports which survived, automatically map the result according to newToOldResultMap. Calls 'getOperandsFunc' with the new instance op, the old instance op, and expects the operand vector to return filled. getOperandsFunc can (and often does) modify other operations. The update call deletes the original instance op, so all references are invalidated after this call.
Definition at line 135 of file MSFTPassCommon.cpp.
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/MSFT/Transforms/MSFTPassCommon.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/MSFT/Transforms/MSFTPassCommon.cpp
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/MSFT/Transforms/MSFTWireCleanup.cpp