CIRCT: circt::esi::capnp::detail::CapnpTypeSchemaImpl Struct Reference
circt::esi::capnp::detail::CapnpTypeSchemaImpl Struct Reference
Actual implementation of CapnpTypeSchema to keep all the details out of the header.
Public Member Functions
CapnpTypeSchemaImpl (CapnpTypeSchema &base)
CapnpTypeSchemaImpl (const CapnpTypeSchemaImpl &)=delete
LogicalResult write (llvm::raw_ostream &os) const
This function is essentially a placeholder which only supports ints.
bool operator== (const CapnpTypeSchemaImpl &) const
size_t size () const
hw::HWModuleOp buildEncoder (Value clk, Value valid, Value)
Build an HW/SV dialect capnp encoder for this type.
hw::HWModuleOp buildDecoder (Value clk, Value valid, Value)
Build an HW/SV dialect capnp decoder for this type.
Private Member Functions
::capnp::ParsedSchema getSchema () const
Write a valid capnp schema to memory, then parse it out of memory using the capnp library.
::capnp::StructSchema getCapnpTypeSchema () const
Find the schema corresponding to type and return it.
Private Attributes
CapnpTypeSchema & base
::capnp::SchemaParser parser
mutable ::capnp::ParsedSchema rootSchema
mutable ::capnp::StructSchema typeSchema
Detailed Description
Actual implementation of CapnpTypeSchema to keep all the details out of the header.
Definition at line 54 of file Schema.cpp.
Constructor & Destructor Documentation
CapnpTypeSchemaImpl() [1/2]
CapnpTypeSchemaImpl::CapnpTypeSchemaImpl (CapnpTypeSchema & base)
Definition at line 145 of file Schema.cpp.
CapnpTypeSchemaImpl() [2/2]
circt::esi::capnp::detail::CapnpTypeSchemaImpl::CapnpTypeSchemaImpl (const CapnpTypeSchemaImpl &) delete
Member Function Documentation
buildDecoder()
hw::HWModuleOp CapnpTypeSchemaImpl::buildDecoder (Value clk, Value valid, Value operandVal)
Build an HW/SV dialect capnp decoder for this type.
Build an HW/SV dialect capnp decoder module for this type.
Outputs packed and unpadded data.
Definition at line 966 of file Schema.cpp.
References base, decodeField(), getCapnpTypeSchema(), circt::esi::ESIAPIType::getFields(), circt::esi::ESIAPIType::getType(), circt::hw::INPUT, circt::esi::ESIAPIType::name(), circt::hw::OUTPUT, and size().
buildEncoder()
hw::HWModuleOp CapnpTypeSchemaImpl::buildEncoder (Value clk, Value valid, Value operandVal)
Build an HW/SV dialect capnp encoder for this type.
Build an HW/SV dialect capnp encoder module for this type.
Inputs need to be packed and unpadded.
Definition at line 791 of file Schema.cpp.
References base, circt::calyx::direction::get(), getCapnpTypeSchema(), circt::esi::ESIAPIType::getType(), circt::hw::INPUT, circt::esi::ESIAPIType::name(), circt::hw::OUTPUT, and size().
getCapnpTypeSchema()
capnp::StructSchema CapnpTypeSchemaImpl::getCapnpTypeSchema () const private
Find the schema corresponding to type and return it.
Definition at line 178 of file Schema.cpp.
References base, getSchema(), circt::esi::ESIAPIType::typeID(), and typeSchema.
Referenced by buildDecoder(), buildEncoder(), and size().
getSchema()
capnp::ParsedSchema CapnpTypeSchemaImpl::getSchema () const private
Write a valid capnp schema to memory, then parse it out of memory using the capnp library.
Writing and parsing text within a single process is ugly, but this is by far the easiest way to do this. This isn't the use case for which Cap'nProto was designed.
Definition at line 151 of file Schema.cpp.
References circt::esi::capnp::emitCapnpID(), parser, rootSchema, and write().
Referenced by getCapnpTypeSchema().
operator==()
bool circt::esi::capnp::detail::CapnpTypeSchemaImpl::operator== (const CapnpTypeSchemaImpl &) const
size()
size_t CapnpTypeSchemaImpl::size () const
Definition at line 227 of file Schema.cpp.
References base, getCapnpTypeSchema(), circt::esi::ESIAPIType::getFields(), and size().
Referenced by buildDecoder(), and buildEncoder().
write()
LogicalResult CapnpTypeSchemaImpl::write (llvm::raw_ostream & rawOS) const
This function is essentially a placeholder which only supports ints.
It'll need to be re-worked when we start supporting structs, arrays, unions, enums, etc.
Definition at line 279 of file Schema.cpp.
References base, emitCapnpType(), circt::esi::ESIAPIType::getFields(), and circt::esi::capnp::CapnpTypeSchema::writeMetadata().
Referenced by getSchema().
Member Data Documentation
base
CapnpTypeSchema& circt::esi::capnp::detail::CapnpTypeSchemaImpl::base private
Definition at line 74 of file Schema.cpp.
Referenced by buildDecoder(), buildEncoder(), getCapnpTypeSchema(), size(), and write().
parser
::capnp::SchemaParser circt::esi::capnp::detail::CapnpTypeSchemaImpl::parser private
Definition at line 76 of file Schema.cpp.
Referenced by getSchema().
rootSchema
mutable ::capnp::ParsedSchema circt::esi::capnp::detail::CapnpTypeSchemaImpl::rootSchema private
Definition at line 77 of file Schema.cpp.
Referenced by getSchema().
typeSchema
mutable ::capnp::StructSchema circt::esi::capnp::detail::CapnpTypeSchemaImpl::typeSchema private
Definition at line 78 of file Schema.cpp.
Referenced by getCapnpTypeSchema().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/capnp/Schema.cpp