CIRCT: VisitingSet Struct Reference
VisitingSet Struct Reference
A value is in VisitingSet if its subtree is still being traversed.
Public Member Functions
void appendEmpty ()
void appendToEnd (SmallVector< Value > &values)
bool contains (Value v)
void popUntilVal (Value v, const llvm::function_ref< void(Value poppedVal)> f={})
Private Attributes
SmallVector< SmallVector< Value, 2 > > visitingStack
The stack is maintained to keep track of the cycle, if one is found.
DenseMap< Value, unsigned > valToStackMap
This map of the Visiting values, is for faster query, to check if a Value is in VisitingSet.
Detailed Description
A value is in VisitingSet if its subtree is still being traversed.
That is, all its children have not yet been visited. If any Value is visited while its still in the VisitingSet, that implies a back edge and a cycle.
Definition at line 53 of file CheckCombLoops.cpp.
Member Function Documentation
appendEmpty()
void VisitingSet::appendEmpty () inline
Definition at line 66 of file CheckCombLoops.cpp.
Referenced by DiscoverLoops::processModule().
appendToEnd()
void VisitingSet::appendToEnd (SmallVector< Value > & values) inline
Definition at line 67 of file CheckCombLoops.cpp.
Referenced by DiscoverLoops::processModule().
contains()
bool VisitingSet::contains (Value v) inline
Definition at line 73 of file CheckCombLoops.cpp.
Referenced by DiscoverLoops::processModule().
popUntilVal()
void VisitingSet::popUntilVal (Value v, const llvm::function_ref< void(Value poppedVal)> f = {}) inline
Definition at line 78 of file CheckCombLoops.cpp.
Referenced by DiscoverLoops::processModule(), and DiscoverLoops::reportLoopFound().
Member Data Documentation
valToStackMap
DenseMap<Value, unsigned> VisitingSet::valToStackMap private
This map of the Visiting values, is for faster query, to check if a Value is in VisitingSet.
It also records the corresponding index into the visitingStack, for faster pop until the Value.
Definition at line 63 of file CheckCombLoops.cpp.
visitingStack
SmallVector<SmallVector<Value, 2> > VisitingSet::visitingStack private
The stack is maintained to keep track of the cycle, if one is found.
This is required for an iterative DFS traversal, its implicitly recorded for a recursive version of this algorithm. Each entry in the stack is a list of aliasing Values, which were visited at the same time.
Definition at line 59 of file CheckCombLoops.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp