CIRCT: Evaluator Struct Reference
Evaluator Struct Reference
Provides an Evaluator class by simply wrapping the OMEvaluator CAPI.
Public Member Functions
Evaluator (MlirModule mod)
Object instantiate (MlirAttribute className, std::vector< MlirAttribute > actualParams)
MlirModule getModule ()
Private Attributes
OMEvaluator evaluator
Detailed Description
Provides an Evaluator class by simply wrapping the OMEvaluator CAPI.
Definition at line 57 of file OMModule.cpp.
Constructor & Destructor Documentation
Evaluator()
Evaluator::Evaluator (MlirModule mod) inline
Definition at line 59 of file OMModule.cpp.
Member Function Documentation
getModule()
MlirModule Evaluator::getModule () inline
Definition at line 80 of file OMModule.cpp.
References omEvaluatorGetModule().
instantiate()
Object Evaluator::instantiate (MlirAttribute className, std::vector< MlirAttribute > actualParams) inline
Definition at line 62 of file OMModule.cpp.
References omEvaluatorInstantiate(), and omEvaluatorObjectIsNull().
Member Data Documentation
evaluator
OMEvaluator Evaluator::evaluator private
Definition at line 84 of file OMModule.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/OMModule.cpp