CIRCT: Object Struct Reference
Object Struct Reference
Provides an Object class by simply wrapping the OMObject CAPI.
Public Member Functions
Object (OMObject object)
MlirType getType ()
Get the Type from an Object, which will be a ClassType.
std::variant< Object, MlirAttribute > getField (MlirAttribute name)
Private Attributes
OMObject object
Detailed Description
Provides an Object class by simply wrapping the OMObject CAPI.
Definition at line 23 of file OMModule.cpp.
Constructor & Destructor Documentation
Object()
Object::Object (OMObject object) inline
Definition at line 25 of file OMModule.cpp.
Member Function Documentation
getField()
std::variant<Object, MlirAttribute> Object::getField (MlirAttribute name) inline
Definition at line 32 of file OMModule.cpp.
References omEvaluatorObjectGetField(), omEvaluatorObjectValueGetObject(), omEvaluatorObjectValueGetPrimitive(), omEvaluatorObjectValueIsAObject(), omEvaluatorObjectValueIsAPrimitive(), and omEvaluatorObjectValueIsNull().
getType()
MlirType Object::getType () inline
Get the Type from an Object, which will be a ClassType.
Definition at line 28 of file OMModule.cpp.
References omEvaluatorObjectGetType().
Member Data Documentation
object
OMObject Object::object private
Definition at line 53 of file OMModule.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/OMModule.cpp