CIRCT: circt::firrtl::AnnoTarget Struct Reference
circt::firrtl::AnnoTarget Struct Reference
An annotation target is used to keep track of something that is targeted by an Annotation.
#include <FIRRTLAnnotations.h>
Public Member Functions
AnnoTarget (detail::AnnoTargetImpl impl=nullptr)
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
operator bool () const
bool operator== (const AnnoTarget &other) const
bool operator!= (const AnnoTarget &other) const
Operation * getOp () const
void setOp (Operation *op)
AnnotationSet getAnnotations () const
Get the annotations associated with the target.
void setAnnotations (AnnotationSet annotations) const
Set the annotations associated with the target.
FModuleLike getModule () const
Get the parent module of the target.
StringAttr getInnerSym (ModuleNamespace &moduleNamespace) const
Get the inner_sym attribute of an op.
Attribute getNLAReference (ModuleNamespace &moduleNamespace) const
Get a reference to this target suitable for use in an NLA.
FIRRTLType getType () const
Get the type of the target.
detail::AnnoTargetImpl getImpl () const
Protected Attributes
detail::AnnoTargetImpl impl
Detailed Description
An annotation target is used to keep track of something that is targeted by an Annotation.
Definition at line 389 of file FIRRTLAnnotations.h.
Constructor & Destructor Documentation
AnnoTarget()
circt::firrtl::AnnoTarget::AnnoTarget (detail::AnnoTargetImpl impl = nullptr) inline
Definition at line 390 of file FIRRTLAnnotations.h.
Member Function Documentation
cast()
template<typename U > U circt::firrtl::AnnoTarget::cast () const inline
Definition at line 406 of file FIRRTLAnnotations.h.
References impl.
Referenced by addAnnotation().
dyn_cast()
template<typename U > U circt::firrtl::AnnoTarget::dyn_cast () const inline
Definition at line 398 of file FIRRTLAnnotations.h.
References impl.
Referenced by applyConventionAnno(), circt::firrtl::applyWiring(), and circt::firrtl::AnnoPathValue::isOpOfType().
dyn_cast_or_null()
template<typename U > U circt::firrtl::AnnoTarget::dyn_cast_or_null () const inline
Definition at line 402 of file FIRRTLAnnotations.h.
References impl.
Referenced by addAnnotation().
getAnnotations()
AnnotationSet AnnoTarget::getAnnotations () const
Get the annotations associated with the target.
Definition at line 543 of file FIRRTLAnnotations.cpp.
References getOp().
Referenced by Deduper::recordAnnotations().
getImpl()
detail::AnnoTargetImpl circt::firrtl::AnnoTarget::getImpl () const inline
Definition at line 437 of file FIRRTLAnnotations.h.
References impl.
Referenced by circt::firrtl::OpAnnoTarget::classof(), circt::firrtl::PortAnnoTarget::classof(), llvm::DenseMapInfo< circt::firrtl::AnnoTarget >::getHashValue(), getOp(), circt::firrtl::PortAnnoTarget::getPortNo(), setOp(), and circt::firrtl::PortAnnoTarget::setPortNo().
getInnerSym()
StringAttr AnnoTarget::getInnerSym (ModuleNamespace & moduleNamespace) const
Get the inner_sym attribute of an op.
If there is no attached inner_sym, then one will be created and attached to the op.
Definition at line 555 of file FIRRTLAnnotations.cpp.
getModule()
FModuleLike AnnoTarget::getModule () const
Get the parent module of the target.
Definition at line 536 of file FIRRTLAnnotations.cpp.
References getOp().
Referenced by buildNLA().
getNLAReference()
Attribute AnnoTarget::getNLAReference (ModuleNamespace & moduleNamespace) const
Get a reference to this target suitable for use in an NLA.
Definition at line 562 of file FIRRTLAnnotations.cpp.
getOp()
Operation* circt::firrtl::AnnoTarget::getOp () const inline
Definition at line 415 of file FIRRTLAnnotations.h.
References getImpl(), and circt::firrtl::detail::AnnoTargetImpl::getOp().
Referenced by addAnnotation(), applyAttributeAnnotation(), applyConventionAnno(), applyDUTAnno(), applyLoadMemoryAnno(), circt::firrtl::applyWiring(), applyWithoutTargetImpl(), findFieldID(), getAnnotations(), circt::firrtl::OpAnnoTarget::getAnnotations(), circt::firrtl::PortAnnoTarget::getAnnotations(), circt::firrtl::OpAnnoTarget::getInnerSym(), circt::firrtl::PortAnnoTarget::getInnerSym(), getModule(), circt::firrtl::OpAnnoTarget::getNLAReference(), circt::firrtl::PortAnnoTarget::getNLAReference(), circt::firrtl::OpAnnoTarget::getType(), circt::firrtl::PortAnnoTarget::getType(), lowerInternalPathAnno(), circt::firrtl::resolveEntities(), circt::firrtl::OpAnnoTarget::setAnnotations(), circt::firrtl::PortAnnoTarget::setAnnotations(), and updateExpandedPort().
getType()
FIRRTLType AnnoTarget::getType () const
Get the type of the target.
Definition at line 569 of file FIRRTLAnnotations.cpp.
Referenced by circt::firrtl::applyGCTDataTaps(), findFieldID(), and circt::firrtl::resolveEntities().
isa()
template<typename U > bool circt::firrtl::AnnoTarget::isa () const inline
Definition at line 393 of file FIRRTLAnnotations.h.
Referenced by addAnnotation(), applyAttributeAnnotation(), applyDUTAnno(), applyWithoutTarget(), and circt::firrtl::resolveEntities().
operator bool()
circt::firrtl::AnnoTarget::operator bool () const inline
Definition at line 411 of file FIRRTLAnnotations.h.
References impl.
operator!=()
bool circt::firrtl::AnnoTarget::operator!= (const AnnoTarget & other) const inline
Definition at line 413 of file FIRRTLAnnotations.h.
operator==()
bool circt::firrtl::AnnoTarget::operator== (const AnnoTarget & other) const inline
Definition at line 412 of file FIRRTLAnnotations.h.
References impl.
setAnnotations()
void AnnoTarget::setAnnotations (AnnotationSet annotations) const
Set the annotations associated with the target.
Definition at line 550 of file FIRRTLAnnotations.cpp.
Referenced by Deduper::mergeAnnotations().
setOp()
void circt::firrtl::AnnoTarget::setOp (Operation * op) inline
Definition at line 416 of file FIRRTLAnnotations.h.
References getImpl(), and circt::firrtl::detail::AnnoTargetImpl::setOp().
Member Data Documentation
impl
detail::AnnoTargetImpl circt::firrtl::AnnoTarget::impl protected
Definition at line 440 of file FIRRTLAnnotations.h.
Referenced by cast(), dyn_cast(), dyn_cast_or_null(), getImpl(), operator bool(), and operator==().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp